### ISSUE TITLE
Building a JavaScript Wrapper for DrQA

### ISSUE THREAD

**Issue by abdulhannanali** [facebookresearch/DrQA#1]
I can only do JavaScript and therefore would like to build a wrapper around DrQA so it can be easily used in the Node.JS applications in production too. Is this possible to do?

**Comment by ajfisch** [comment]
Hi @abdulhannanali, thanks for checking out the repo! I'm not much of a JavaScript guy myself and there aren't any plans to build such a wrapper. You're welcome to give it a shot though :).
