### ISSUE TITLE
Training with Hindi wikipedia text

### ISSUE THREAD

**Issue by swathimithran** [facebookresearch/DrQA#10]
Hi Adam,

Thanks for the excellent QA system, we installed the system and it is working good on wikipedia dataset.
We need to train the system with Hindi wikipedia, please let us know if this is feasible and if yes, How we need to proceed.

Thanks & Regards,
M Swathi Mithran

**Comment by ajfisch** [comment]
Hi @swathimithran,

Thanks for checking out the repo! DrQA is only trained on English -- we don't have plans to extend it to other languages (there is still much research and improvement to be done in the English domain).

There is nothing specific about the model to English -- you can use a tokenizer suitable for Hindi and Hindi word embeddings (available for example at [fasttext.cc](https://fasttext.cc/docs/en/pretrained-vectors.html)).

The main thing, however, is that you will need training data.
