### ISSUE TITLE
Training DRQA for custom documents

### ISSUE THREAD

**Issue by RitwikGopi** [facebookresearch/DrQA#100]
Is it possible that I can use my own files instead of Wikipedia to train DRQA? @ajfisch

**Comment by vaibhavgeek** [comment]
Please see the document on retriever in this repo. It explains exactly what you want to accomplish

**Comment by vaibhavgeek** [comment]
https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/README.md

**Comment by RitwikGopi** [comment]
@vaibhavgeek Thanks man.
