### ISSUE TITLE
Documentation for how docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz file is created

### ISSUE THREAD

**Issue by murphp15** [facebookresearch/DrQA#107]
Hi Guys I love the project.
Would you be able to explain how docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz was generated? 
Is it accurate to say that the content in that file is a matrix which is 
document size * word size. Each entry in the matrix is a tfidf value?

**Comment by ajfisch** [comment]
This is the result of running 
```
python scripts/retriever/build_tfidf.py /path/to/doc/db /path/to/output/dir --ngram 2 --tokenizer simple --hash 16777216
```

As described in the retriever [readme](https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/README.md).
