### ISSUE TITLE
Custom corpus - document retrieval

### ISSUE THREAD

**Issue by xjurko** [facebookresearch/DrQA#108]
Hi, I am facing following issue which I cannot find a way around. I want to build a QA system that will answer questions about New York (any domain in general). I created a custom corpus of documents. Each of these documents is somehow related to New York City. The string 'New York' is present in every single one of the documents. Many of these documents are Wikipedia articles. 

Issues when running retriever with custom model:
- process("Which rivers flow through New York?", k=N);   returns very irrelevant articles.
- process("What is New York?", k=N) returns no documents at all.

Additionally, when running retriever with full wikipedia dump, both of these queries return relevant articles at the top.

As mentioned in other issues this is probably related to weighing function of ranker:
`IDF = log((N - Nt + 0.5) / (Nt + 0.5))`

I am not really sure how to modify the retriever to work with domain-specific questions and documents.
Since the results are better on a more generic database, one solution may be to extend my corpus with dummy documents but I find it very inelegant.

Any pointers, ideas, suggestions will be much appreciated.
Thanks in advance

**Comment by joshuazweig** [comment]
I've been having the same issue. 
It seems that simply specifying the `--doc-db` argument is insufficient. 
I'm currently exploring two avenues. 1) That the corpus needs to be processed into some particular format or 2) that this option is not implemented.

**Comment by ajfisch** [comment]
Indeed you probably want to change the IDF term. In that formulation, the weight will be negative if the term appears in over half the documents (which for you it does).

So having a very common term appear very frequently will actually down rank the document. Here, because your domain is specific, you don't necessarily want a term like New York to hurt proportional to its frequency in the document.

So try changing the IDF function to `log(1 + N / Nt)` on the query [here](https://github.com/facebookresearch/DrQA/blob/master/drqa/retriever/tfidf_doc_ranker.py#L109) and when you construct the corpus [here](https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/build_tfidf.py#L143).

@joshuazweig, you also need to build and specify the tf-idf corpus, if you haven't done that.

**Comment by joshuazweig** [comment]
Thanks @ajfisch ! 
I've done so, but I don't think correctly. I think the JSON I'm building from is incorrectly formatted. 
```
{"id": "doc1", "text": "text of doc1"}
...
{"id": "docN", "text": "text of docN"}
```

Should "text" be a single line? The retriever is currently unable to pick up any paragraphs.

**Comment by ajfisch** [comment]
That should be fine. Maybe run through it step by step to see where something went wrong.
- Did you build the db?
You can inspect the db you created using `build_db` with:
```
sqlite3
sqlite> .open FILENAME
sqlite> SELECT * FROM documents LIMIT 1;
```

- Did you build the TF-IDF matrix using that db?
- Did you specify both the TF-IDF matrix and db as arguments to the retriever script?

**Comment by joshuazweig** [comment]
Thanks for all of the help! 

The answer to all three of those questions is Yes. 
The reason that I believe there is some issue is that when I run in interactive mode I see the line 
```
04/15/2018 06:00:24 PM: [ Reading 0 paragraphs... ]
```

Could this also be because the system doesn't think any of the documents are relevant? 

I have additionally been trying to troubleshoot by running the retriever in interactive mode. For any question I ask I get a blank table.
```
+------+--------+-----------+
| Rank | Doc Id | Doc Score |
+------+--------+-----------+
+------+--------+-----------+
```

**Comment by ajfisch** [comment]
Yeah, it will be in the document retriever, so let's debug that. What query are you running?

**Comment by joshuazweig** [comment]
I think my issue is in how I am formatting the data with respect to the specification: 
```
{"id": "doc1", "text": "text of doc1"}
...
{"id": "docN", "text": "text of docN"}
``` 

How can I signify paragraph breaks while simultaneously needing to include the entire text on a single line?

**Comment by ajfisch** [comment]
@joshuazweig I'm not sure I am following.

It should work fine with paragraph breaks, indeed the Wikipedia articles have many paragraph breaks.

Here is an example:
```
{"id": "doc1", "text": "text of doc1.\nIt spans multiple lines.\n\nAnd also paragraphs.\nIt is about doc1."}
{"id": "doc2", "text": "text of doc2.\n\nIt has three paragraphs.\n\nThis is the third one."}
{"id": "doc3", "text": "text of doc3. doc3 only has one line."}
```

```
python scripts/retriever/build_db.py /tmp/text.json /tmp/text.db
```

```
python scripts/retriever/build_tfidf.py /tmp/text.db /tmp
```

```
[fisch//scratch/fisch/github/DrQA: (master)]$ python scripts/retriever/interactive.py --model /tmp/text-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
04/22/2018 06:24:33 PM: [ Initializing ranker... ]
04/22/2018 06:24:33 PM: [ Loading /tmp/text-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]

Interactive TF-IDF DrQA Retriever
>> process(question, k=1)
>> usage()

>>> ranker.doc_mat
<16777216x3 sparse matrix of type '<class 'numpy.float64'>'
        with 16 stored elements in Compressed Sparse Row format>
>>> process('get doc2')
+------+--------+-----------+
| Rank | Doc Id | Doc Score |
+------+--------+-----------+
|  1   |  doc2  |  0.12537  |
+------+--------+-----------+
>>> process('get doc3')
+------+--------+-----------+
| Rank | Doc Id | Doc Score |
+------+--------+-----------+
|  1   |  doc3  |  0.19871  |
+------+--------+-----------+
>>> process('get doc1')
+------+--------+-----------+
| Rank | Doc Id | Doc Score |
+------+--------+-----------+
|  1   |  doc1  |  0.19871  |
+------+--------+-----------+
```

**Comment by joshuazweig** [comment]
Thanks for all of the help @ajfisch ! 
Got it working yesterday with some mods to the source. 

Feel free to close out the issue!

**Comment by muni2773** [comment]
Joshua, what were the mods to source ? Would appreciate if you could share. I am having the same issue I think.

**Comment by joshuazweig** [comment]
My issue was that I was not using explicit "\n\n" as paragraph breaks. 
Check out the first few commits on my fork: https://github.com/joshuazweig/Akashwani

**Comment by ajfisch** [comment]
Closing. Feel free to re-open if you have any remaining questions.
