### ISSUE TITLE
GPU config and training time

### ISSUE THREAD

**Issue by anand-ar** [facebookresearch/DrQA#109]
Hi,

Do you have a rough estimate of your dataset size  vs number of layersRNN architecture vs num of GPU cores/RAM you used and training time per epoch?

Thanks

**Comment by ajfisch** [comment]
With a single GPU and 5-10 CPU threads for asynchronous data loading it takes ~250-500s per epoch (depending on your GPU, e.g. M40 vs  K40) with the default settings here.
