### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by nlothian** [facebookresearch/DrQA#11]
Thanks very much for open sourcing DrQA. It's a great piece of work and I'm learning a lot.

I have a question about reader scoring. In the reader, are the scores for different questions on the same document comparable? 

ie, if I use the document https://en.wikipedia.org/wiki/Apple_Inc. and ask "Was Steve Jobs in charge of Apple?" and "Was John Sculley in charge of Apple?" is it reasonable to look at the scores of the answers to both of those and assume the one with the higher score is the better answer (in some way)?

**Comment by ajfisch** [comment]
Hi @nlothian,

I'm glad you like the repo! Unfortunately, as the model is now, it's hard to get reliable confidence scores. You could, however, compare scores to different questions by looking at the non-normalized outputs (which is the default `span_score` reported in the pipeline).

What this means is that you are looking at the raw activations for the spans, and not squashing them to be 0-1 (relative to the other scores for that question) with a softmax.

For some question pairs comparing their answers' raw output scores will make sense, for others not so much (the model might pick up strongly on some subtle attribute).

As a side note, the DrQA model does not currently handle yes/no questions, only factoid questions (which it answers with extractive methods).

**Comment by nlothian** [comment]
Thanks! That makes sense (and yes, I realize about the lack of yes/no handling). 

So it looks like I should be able to do this by adding `'normalize' : False` in [DEFAULTS](https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/__init__.py#L15), or maybe there is a way to pass this via a command line parameter?

Or is the [softmax this argument turns off](https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/layers.py#L247) not the one you are referring to?

**Comment by ajfisch** [comment]
This is a parameter in initializing the DocReader model: https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/model.py#L32-L33

You can see in the full pipeline that I initialize with normalization off:
https://github.com/facebookresearch/DrQA/blob/master/drqa/pipeline/drqa.py#L113

Unfortunately this is not an argument to the reader Predictor. But I will push a change that will add that here:
https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/predictor.py#L48-L59

**Comment by nlothian** [comment]
I thought I'd traced that through and that argument ends up being used where I linked above. I must have missed something though.

 I was looking at 
https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/predictor.py#L59 and thought I could override the normalize parameter there.

**Comment by ajfisch** [comment]
Indeed you traced where it ends up being used correctly :). I was just pointing you to the higher level place where you can set it without much pain (we link to the same line in predictor.py).

**Comment by ajfisch** [comment]
done.
