### ISSUE TITLE
Adding New Data & Hiring Resourcefull People 

### ISSUE THREAD

**Issue by augmen** [facebookresearch/DrQA#111]
I am new .how to add fed  data / new articles to predict the answers ? how to add the data like books , research papers , news articles etc. to the Dr.QnA ?

**Comment by augmen** [comment]
where to hire the Necessary talent to develop DrQA ?

**Comment by ajfisch** [comment]
Welcome! Take a look at the READMEs, specifically on how to work with the different DrQA [components](https://github.com/facebookresearch/DrQA#drqa-components).

This repository serves as a platform for researchers, students, and practitioners to view the code to better understand the paper, reproduce results, and build on top of it on their own to newer, better ideas. It's open research, so anyone can develop it!
