### ISSUE TITLE
[Question] what Version of wikipedia about SQUAD? 

### ISSUE THREAD

**Issue by hxsnow10** [facebookresearch/DrQA#112]
I see you use 2016-12-21 of wikipedia.  

When i use latest version,  i  find wikipedia articles with same title as SQUAD but don't have
expected sent/context of answer.
  
So i want know, your choose of 2016-12-21 is made randomly, or SQUAD is extract from 2016-12-21?

Thanks!

**Comment by ajfisch** [comment]
`2016-12-21` was the published Wikipedia dump available when we did the research.  SQuAD is from an earlier dump.
