### ISSUE TITLE
unable to insert documents in DB using build_db.py 

### ISSUE THREAD

**Issue by anjalisangwan68** [facebookresearch/DrQA#118]
Traceback (most recent call last):
  File "build_db.py", line 151, in <module>
    args.data_path, args.save_path, args.preprocess, args.num_workers
  File "build_db.py", line 121, in store_contents
    c.executemany("INSERT INTO documents VALUES (?,?)",str(pairs))
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.   ....

pairs contains both the DOC ID and Text ....its a list but with just one element though ...can you please help how to insert custom document to the retriever ?

**Comment by anjalisangwan68** [comment]
the code works fine if the TXT file has single line text .but if it has paragraphs then it fails .

**Comment by krutikabapat** [comment]
@anjalisangwan68  I am facing the same issue. Were you able to solve it?  Urgent help is required.
