### ISSUE TITLE
build_db.py

### ISSUE THREAD

**Issue by augmen** [facebookresearch/DrQA#121]
what  this scripts build_db.py does ? As i gone through the Readme.md doc i can see that To create a sqlite db from a corpus of documents, run:

```bash
python build_db.py /path/to/data /path/to/saved/db.db
```

which can return the xtx file to sqlite database format doc.db in the following format 

```python
{"id": "doc1", "text": "text of doc1"}
...
{"id": "docN", "text": "text of docN"}
```

Right ?

Please guide

**Comment by ajfisch** [comment]
Please see the retriever readme for a description.
