### ISSUE TITLE
Retriever Eval Problem

### ISSUE THREAD

**Issue by hxsnow10** [facebookresearch/DrQA#123]
Hello,
    I have some question about the method you do in Retriever Eval.
```python
def has_answer(answer, doc_id, match):
    """Check if a document contains an answer string.
    If `match` is string, token matching is done between the text and answer.
    If `match` is regex, we search the whole text with the regex.
    """
```
Then you get 77.8 recall.
But when i use extact doc title matchiing, i get about only  59.

Obviously, your method may has some problem, when doc content contain true answer but not true context matching.
How do you think of this problem?

Thanks!

**Comment by ajfisch** [comment]
I'm sorry, I don't think I understand your question. What do you mean by "exact doc title matching" ?

The function does what the doc string says "Check if a document contains an answer string". We don't verify that the context is "correct" or "complete" --- the difficulty of doing this automatically is on par or harder than the machine reading task itself. So, obviously, the metrics here are upper bounds.

**Comment by ajfisch** [comment]
By "exact doc title matching" do you mean when the true SQuAD document from which the question originated is retrieved?

Yes, you are right, this metric is not measuring that. But we're not solely interested in that; SQuAD is based off of the most popular Wikipedia pages, the content is not unique. Many other pages have valid answers as well -- and we're no longer interested in restricting ourselves to just SQuAD, but rather "machine reading at scale".

Machine reading at scale, as you point out, is indeed significantly harder. The contexts being given by the retriever are not guaranteed to be on topic and/or might be misleading. This is part of the challenge, but as I said earlier, not something this evaluation measures.

**Comment by ajfisch** [comment]
Closing, as it is a conceptual issue.
