### ISSUE TITLE
What should the format of the data for retriever system.

### ISSUE THREAD

**Issue by ankitraj999** [facebookresearch/DrQA#124]
I have my data in .txt format. I converted its data format as given in README section of retriever folder..like below
{"id": "doc1", "text": "text of doc1"}
...
{"id": "docN", "text": "text of docN"}

I am executing following command:
python build_db.py /path/to/data  /path/to/saved/db.db
giving the path of my data which is in .txt format and path where I want to save .db file

python build_db.py '/wikipedia/dictionary.txt' '/wikipedia/ab.db'
04/27/2018 06:27:26 PM: [ Reading into database... ]
Traceback (most recent call last):
  File "build_db.py", line 136, in <module>
    args.data_path, args.save_path, args.preprocess, args.num_workers
  File "build_db.py", line 101, in store_contents
    conn = sqlite3.connect(save_path)
sqlite3.OperationalError: unable to open database file
Should I change the data in some specific format(like .npy)  with some specific orientation?

**Comment by ajfisch** [comment]
Try https://stackoverflow.com/questions/4636970/sqlite3-operationalerror-unable-to-open-database-file

**Comment by ajfisch** [comment]
Closing for now, feel free to reopen if the problem persists.
