### ISSUE TITLE
getting empty results even though related text available in content

### ISSUE THREAD

**Issue by shivamani-ans** [facebookresearch/DrQA#126]
Hi,

we have a paragraph from content as below 

"The unit of power is watt [in honour of James Watt (1736 – 1819)] having the symbol W. 1 watt is the power of an agent, which does work at the rate of 1 joule per second. We can also say that power is 1 W when the rate of consumption of energy is 1 J s–1."

input question: process('what is unit of power')

response: empty results (no doc-score and answer-score)

ex-2: 
"A solution is a homogeneous mixture of two or more substances. You come across various types of solutions in your daily life. Lemonade, soda water etc. are all examples of solutions. Usually we think of a solution as a liquid that contains either a solid, liquid or a gas dissolved in it. But, we can also have solid solutions (alloys) and gaseous solutions (air). In a solution there is homogeneity at the particle level. For example, lemonade tastes the same throughout. This shows that particles of sugar or salt are evenly distributed in the solution."

input question: process('what is a solution')

response: empty results (no doc-score and answer-score)

can i know what is the issue from my side ?

**Comment by Mohan-Zhang-u** [comment]
Hi, I debugged and found that the reason is, the TF-IDF retriever only works when you put in more than 3 articles.
