### ISSUE TITLE
getting irrelevant answers with large answer scores

### ISSUE THREAD

**Issue by shivamani-ans** [facebookresearch/DrQA#127]
Hi,

for few of the questions we are getting large answer scores .Dose this indicates a unusual behavior due to any error/bug  or is it expected result. I'm attaching screen shots. Pls  have look at it

![screenshot_20](https://user-images.githubusercontent.com/28960925/39472160-1a4f7ee4-4d65-11e8-81d0-bae3fbe1280b.png)
![screenshot_21](https://user-images.githubusercontent.com/28960925/39472161-1a7c0806-4d65-11e8-8122-089e5a96fd5e.png)

**Comment by ajfisch** [comment]
There doesn't appear to be a bug here, beyond what appears to be the model overfitting to some aspect about the text.
