### ISSUE TITLE
eq() TypeError in train.py

### ISSUE THREAD

**Issue by smiduthuri** [facebookresearch/DrQA#128]
Hi,

I've been trying to run the train.py file, and am facing the following error:

```
Traceback (most recent call last):
  File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 484, in main
    validate_unofficial(args, train_loader, model, stats, mode='train')
  File "scripts/reader/train.py", line 253, in validate_unofficial
    accuracies = eval_accuracies(pred_s, target_s, pred_e, target_e)
  File "scripts/reader/train.py", line 345, in eval_accuracies
    if any([1 for _s, _e in zip(target_s[i], target_e[i])
  File "scripts/reader/train.py", line 346, in <listcomp>
    if _s == pred_s[i] and _e == pred_e[i]]):
TypeError: eq() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
 * (float other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
```

I see that there is some code above to convert 1D tensors to list of lists:

```
# Convert 1D tensors to lists of lists (compatibility)
    if torch.is_tensor(target_s):
        target_s = [[e] for e in target_s]
        target_e = [[e] for e in target_e]
```

The type of pred_s[i] is numpy.ndarray.

The type of target_s[i][0] is torch.Tensor.

I'm not completely well versed with torch, so I am requesting for help, and proceeding to try to convert the torch.Tensor into a numpy.ndarray during comparison. Any help on fixing this error properly would be appreciated.

Thank you.

**Comment by smiduthuri** [comment]
I've corrected the error by doing the following:

```
_s    --->    np.int64(_s)
pred_s[i]    --->    pred_s[i][0]
_e    --->    np.int64(_e)
pred_e[i]    --->    pred_e[i][0]
```
Is this a good (robust) solution, or is there anything better I should try?

**Comment by ajfisch** [comment]
I can't reproduce your error -- what version of Python/Pytorch are your running? Have you made any changes? What command are you running?

**Comment by smiduthuri** [comment]
I'm running PyTorch 0.4.0 on Python 3.6.5. I've used the example command for training, given in the README.md at https://github.com/facebookresearch/DrQA/tree/master/scripts/reader :

`python scripts/reader/train.py --embedding-file glove.840B.300d.txt --tune-partial 1000`

Currently, other than those changes I have shown in my previous comment, I have also made a change at the beginning of the train.py script to allow the "from drqa import tokenizers" statement to find the drqa folder.

```
project_path = os.getcwd()
while os.path.basename(project_path) != 'DrQA':
    project_path = os.path.dirname(project_path)
sys.path.append(project_path)
```

I didn't suspect this change of causing any issues, though.

**Comment by ajfisch** [comment]
Right now this repository supports PyTorch 3.1 (and 2.0). Pytorch 4.0 has some changes to the way tensors and variables store data that is likely breaking it for you.

**Comment by smiduthuri** [comment]
Probably, yes. I'm running the training with those changes to the variables, and it seems to be running fine for about 13 epochs now.

Shall I leave it as it is, and close the issue if the training completes without any further issues caused by this?

**Comment by ajfisch** [comment]
Yeah, I think the difference here is that Pytorch 0.4 support 0 dimensional tensors, so `[[e] for e in target_s]` doesn't actually convert a tensor to python numbers (as you found). You can do what you do now, or I believe `[[e.item()] for e in target_s]` would also work.

If it hasn't crashed in 13 epochs, it sounds like your fix is doing just fine :).

**Comment by rohanpai** [comment]
I am getting this error as well

**Comment by smiduthuri** [comment]
@ajfisch Yes, training upon the SQuAD dataset has worked with those changes. Thank you.

@rohanpai Even after implementing the fix?
