### ISSUE TITLE
WikiExtractor usage

### ISSUE THREAD

**Issue by jplu** [facebookresearch/DrQA#129]
Hello,
I would like to train the document reader with a more updated Wikipedia dump and my own NLP toolkit. I did extend the source code to take into account my NLP toolkit, and now I need to preprocess the Wikipedia dump with WikiExtractor in order to be able to use the [preprocess](https://github.com/facebookresearch/DrQA/blob/master/scripts/reader/preprocess.py) script.

What is the WikiExtractor command line you used? Any specific options?

Thanks!

**Comment by ajfisch** [comment]
Hi, I used the [WikiExtractor](https://github.com/attardi/wikiextractor) with the default arguments + `--filter_disambig_pages` and `--json` and `--processes <num cpu>`.

**Comment by jplu** [comment]
Thanks a lot!
