### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by RitwikGopi** [facebookresearch/DrQA#13]
Tried running interactive demo. Got the below error. 
```08/02/2017 03:41:14 PM: [ Running on CPU only. ]
08/02/2017 03:41:14 PM: [ Initializing pipeline... ]
08/02/2017 03:41:14 PM: [ Initializing document ranker... ]
08/02/2017 03:41:14 PM: [ Loading /home/ritwik/smartron/rd/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
Traceback (most recent call last):
  File "scripts/pipeline/interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/ritwik/smartron/rd/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
    self.ranker = ranker_class(**ranker_opts)
  File "/home/ritwik/smartron/rd/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
    matrix, metadata = utils.load_sparse_csr(tfidf_path)
  File "/home/ritwik/smartron/rd/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
    matrix = sp.csr_matrix((loader['data'], loader['indices'],
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 233, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/format.py", line 664, in read_array
    array = numpy.ndarray(count, dtype=dtype)
MemoryError```

**Comment by tiru1930** [comment]
same issue here to this is because of ram size, tfidif model is around 13 GB 
 free -h
              total        used        free      shared  buff/cache   available
Mem:            14G        3.2G        8.0G        138M        3.5G         11G
Swap:            0B          0B          0B

**Comment by ajfisch** [comment]
Hi,

Indeed you will need a machine with sufficient RAM to run on the full Wikipedia. Preferably >15-20gb to be safe, though I have comfortably run it on a 15in MacBook (16gb RAM).

I can try to release a "skinny" version with say the top 100,000 popular Wikipedia documents that could be useful for people to try with more commodity hardware (though it won't reproduce our results, obviously).

**Comment by RitwikGopi** [comment]
Is there any other work around for this? Is there a way we can access wiki data from a db or like in chunks?

**Comment by RitwikGopi** [comment]
I am getting the same error even after using a 24GB linux machine. Any idea why this could be happening?

**Comment by ajfisch** [comment]
Not really. Are you perhaps running other processes that compete for memory?

**Comment by RitwikGopi** [comment]
Nope. Less than 600MB only used

**Comment by RitwikGopi** [comment]
Sorry man, I am not getting this error. The error is different. Another user has mentioned the actual error. I will comment there
