### ISSUE TITLE
finding difficulty  in executing distant supervision-Generate.py

### ISSUE THREAD

**Issue by rajashekar2012** [facebookresearch/DrQA#134]
Hi,

I have prepared 100 question and answer as per **format** **A**, given input to distant supervision which is outputting empty .dstrain file.

I got stuck here, I would like to train with these question and answers.
Can I get help to resolve the issue?

**Comment by ajfisch** [comment]
Can you give some examples?

**Comment by rajashekar2012** [comment]
Hi,
In the mean time I have got a chance to go through the code and started debugging. When I asked a question "Explain melting point", we observed that, even though there is an exact match of the answer in the extracted passages is not coming in the .dstrain file. Also observed that the token Melting point did not identified under net, do we have any provision to make melting point to be identified under net.

Other question is regarding training using generated .dstrain file, we observed both train file and Dev file need to be provided as input to train.py, what is the necessity of Dev file and what should be provided under dev file.

**Comment by ajfisch** [comment]
1) You can modify the distant supervision heuristics to filter out fewer documents.

2) We found that using the standard processed Squad dev file for training multi-task works well. If you are fine tuning, you will want to use the dsdev file instead.
