### ISSUE TITLE
Error using WebQuestions data for training

### ISSUE THREAD

**Issue by muni2773** [facebookresearch/DrQA#138]
Hi Aj, not sure why there is a dictionary key error below. 

(pt31) ubuntu@gpu-demo:~/qa$ python scripts/reader/train.py --embedding-file glove.840B.300d.txt --tune-partial 1000 --parallel t --model-dir data/reader --model-name WebQuestions --train-file WebQuestions-train.dstrain --dev-file WebQuestions-train.dsdev --use-pos f --use-ner f --use-lemma f --pretrained data/reader/multitask.mdl

WARN: fix_embeddings set to False as tune_partial > 0.

05/11/2018 03:57:33 PM: [ COMMAND: scripts/reader/train.py --embedding-file glove.840B.300d.txt --tune-partial 1000 --parallel t --model-dir data/reader --model-name WebQuestions --train-file WebQuestions-train.dstrain --dev-file WebQuestions-train.dsdev --use-pos f --use-ner f --use-lemma f --pretrained data/reader/multitask.mdl ]

05/11/2018 03:57:33 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:33 PM: [ Load data files ]

05/11/2018 03:57:34 PM: [ Num train examples = 5400 ]

05/11/2018 03:57:34 PM: [ Num dev examples = 1800 ]

05/11/2018 03:57:34 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:34 PM: [ Using pretrained model... ]

05/11/2018 03:57:34 PM: [ Loading model data/reader/multitask.mdl ]

05/11/2018 03:57:35 PM: [ Overriding saved dropout_rnn: 0.35 --> 0.4 ]

05/11/2018 03:57:35 PM: [ Overriding saved dropout_emb: 0.35 --> 0.4 ]

05/11/2018 03:57:41 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:41 PM: [ Counting 1000 most frequent question words ]

05/11/2018 03:57:41 PM: [ ('?', 5400) ]

05/11/2018 03:57:41 PM: [ ('what', 2795) ]

05/11/2018 03:57:41 PM: [ ('the', 1865) ]

05/11/2018 03:57:41 PM: [ ('is', 1418) ]

05/11/2018 03:57:41 PM: [ ('where', 1264) ]

05/11/2018 03:57:41 PM: [ ... ]

05/11/2018 03:57:41 PM: [ ('went', 5) ]

05/11/2018 03:57:41 PM: [ ('milk', 5) ]

05/11/2018 03:57:41 PM: [ ('meaning', 5) ]

05/11/2018 03:57:41 PM: [ ('verizon', 5) ]

05/11/2018 03:57:41 PM: [ ('staten', 5) ]

05/11/2018 03:57:44 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:44 PM: [ Make data loaders ]

05/11/2018 03:57:44 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:44 PM: [ CONFIG:

{

    "batch_size": 32,

    "checkpoint": false,

    "concat_rnn_layers": true,

    "cuda": true,

    "data_dir": "/home/ubuntu/qa/data/datasets",

    "data_workers": 5,

    "dev_file": "/home/ubuntu/qa/data/datasets/WebQuestions-train.dsdev",

    "dev_json": "/home/ubuntu/qa/data/datasets/SQuAD-v1.1-dev.json",

    "display_iter": 25,

    "doc_layers": 3,

    "dropout_emb": 0.4,

    "dropout_rnn": 0.4,

    "dropout_rnn_output": true,

    "embed_dir": "/home/ubuntu/qa/data/embeddings",

    "embedding_dim": 300,

    "embedding_file": "/home/ubuntu/qa/data/embeddings/glove.840B.300d.txt",

    "expand_dictionary": false,

    "fix_embeddings": false,

    "gpu": -1,

    "grad_clipping": 10,

    "hidden_size": 128,

    "learning_rate": 0.1,

    "log_file": "data/reader/WebQuestions.txt",

    "max_len": 15,

    "model_dir": "data/reader",

    "model_file": "data/reader/WebQuestions.mdl",

    "model_name": "WebQuestions",

    "model_type": "rnn",

    "momentum": 0,

    "no_cuda": false,

    "num_epochs": 40,

    "official_eval": true,

    "optimizer": "adamax",

    "parallel": true,

    "pretrained": "data/reader/multitask.mdl",

    "question_layers": 3,

    "question_merge": "self_attn",

    "random_seed": 1013,

    "restrict_vocab": true,

    "rnn_padding": false,

    "rnn_type": "lstm",

    "sort_by_len": true,

    "test_batch_size": 128,

    "train_file": "/home/ubuntu/qa/data/datasets/WebQuestions-train.dstrain",

    "tune_partial": 1000,

    "uncased_doc": false,

    "uncased_question": false,

    "use_in_question": true,

    "use_lemma": false,

    "use_ner": false,

    "use_pos": false,

    "use_qemb": true,

    "use_tf": true,

    "valid_metric": "f1",

    "weight_decay": 0

} ]

05/11/2018 03:57:45 PM: [ ---------------------------------------------------------------------------------------------------- ]

05/11/2018 03:57:45 PM: [ Starting training... ]

/home/ubuntu/qa/drqa/reader/layers.py:84: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().

  rnn_output = self.rnns[i](rnn_input)[0]

05/11/2018 03:57:49 PM: [ train: Epoch = 0 | iter = 0/169 | loss = 2.66 | elapsed time = 4.39 (s) ]

05/11/2018 03:58:03 PM: [ train: Epoch = 0 | iter = 25/169 | loss = 2.44 | elapsed time = 18.54 (s) ]

05/11/2018 03:58:17 PM: [ train: Epoch = 0 | iter = 50/169 | loss = 2.67 | elapsed time = 32.66 (s) ]

05/11/2018 03:58:31 PM: [ train: Epoch = 0 | iter = 75/169 | loss = 2.40 | elapsed time = 46.56 (s) ]

05/11/2018 03:58:45 PM: [ train: Epoch = 0 | iter = 100/169 | loss = 2.38 | elapsed time = 60.46 (s) ]

05/11/2018 03:58:59 PM: [ train: Epoch = 0 | iter = 125/169 | loss = 2.13 | elapsed time = 74.18 (s) ]

05/11/2018 03:59:13 PM: [ train: Epoch = 0 | iter = 150/169 | loss = 2.43 | elapsed time = 88.20 (s) ]

05/11/2018 03:59:23 PM: [ train: Epoch 0 done. Time for epoch = 98.20 (s) ]

/home/ubuntu/qa/drqa/reader/layers.py:137: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().

  outputs.append(self.rnns[i](rnn_input)[0])

05/11/2018 04:00:19 PM: [ train valid unofficial: Epoch = 0 | start = 83.78 | end = 83.43 | exact = 81.54 | examples = 5400 | valid time = 55.89 (s) ]

05/11/2018 04:00:25 PM: [ dev valid unofficial: Epoch = 0 | start = 81.28 | end = 80.72 | exact = 78.33 | examples = 1800 | valid time = 6.23 (s) ]

Traceback (most recent call last):

  File "scripts/reader/train.py", line 542, in <module>

    main(args)

  File "scripts/reader/train.py", line 492, in main

    dev_offsets, dev_texts, dev_answers)

  File "scripts/reader/train.py", line 298, in validate_official

    prediction = texts[ex_id[i]][s_offset:e_offset]

KeyError: 'cabda9fd6e1e40ff864c6f66cfe2f867'

**Comment by muni2773** [comment]
Thanks AJ, 

Tried that earlier. The problem is in the code base below which expects an f1 result even though official eval is turned off. 

# Validate official
        if args.official_eval:
            result = validate_official(args, dev_loader, model, stats,
                                       dev_offsets, dev_texts, dev_answers)

        # Save best valid
        if result[args.valid_metric] > stats['best_valid']:
            logger.info('Best valid: %s = %.2f (epoch %d, %d updates)' %
                        (args.valid_metric, result[args.valid_metric],
                         stats['epoch'], model.updates))
            model.save(args.model_file)
            stats['best_valid'] = result[args.valid_metric]

**Comment by ajfisch** [comment]
Right, you can change the metric with `--valid-metric exact_match`

**Comment by muni2773** [comment]
Thanks AJ
