### ISSUE TITLE
I don't get any answers with interactive.py 

### ISSUE THREAD

**Issue by x13machine** [facebookresearch/DrQA#139]
>>> process('What is the answer to life, the universe, and everything?')
+------+---------------------------------------------------+-----------+
| Rank |                       Doc Id                      | Doc Score |
+------+---------------------------------------------------+-----------+
|  1   | Phrases from The Hitchhiker's Guide to the Galaxy |   141.26  |
+------+---------------------------------------------------+-----------+

>>> process('what is the age of the universe?')
+------+----------+-----------+
| Rank |  Doc Id  | Doc Score |
+------+----------+-----------+
|  1   | Universe |   102.79  |
+------+----------+-----------+

>>> process('What is question answering?')
+------+--------------------+-----------+
| Rank |       Doc Id       | Doc Score |
+------+--------------------+-----------+
|  1   | Question answering |   327.89  |
+------+--------------------+-----------+

**Comment by ajfisch** [comment]
Are you using `scripts/retriever/interactive.py` or `scripts/pipeline/interactive.py`

**Comment by x13machine** [comment]
ok I had to use scripts/pipeline/interactive.py
