### ISSUE TITLE
Timeout exceeded while running the interactive demo for reader system QandA model

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/DrQA#14]
08/02/2017 10:12:38 AM: [ CUDA enabled (GPU -1) ]
08/02/2017 10:12:38 AM: [ Initializing model... ]
08/02/2017 10:12:38 AM: [ Loading model /usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/data/reader/single.mdl ]
08/02/2017 10:12:44 AM: [ Initializing tokenizer... ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/reader/interactive.py", line 50, in <module>
    predictor = Predictor(args.model, args.tokenizer, num_workers=0)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/reader/predictor.py", line 82, in __init__
    self.tokenizer = tokenizer_class(annotators=annotators)
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/usr/local/lib/python3.5/dist-packages/drqa-0.1.0-py3.5.egg/drqa/tokenizers/corenlp_tokenizer.py", line 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f2aa70a0a58>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'0;ubuntu@ip-172-31-55-21: ~/DrQA/DrQA\x07\x1b[01;32mubuntu@ip-172-31-55-21\x1b[00m:\x1b[01;34m~/DrQA/DrQA\x1b[00m$ '
before (last 100 chars): b'0;ubuntu@ip-172-31-55-21: ~/DrQA/DrQA\x07\x1b[01;32mubuntu@ip-172-31-55-21\x1b[00m:\x1b[01;34m~/DrQA/DrQA\x1b[00m$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 15216
child_fd: 12
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"

**Comment by ajfisch** [comment]
Hi,

This is an issue with your CoreNLP. Have you installed it as explained in the README? https://github.com/facebookresearch/DrQA#installing-drqa

**Comment by liujinyan12** [comment]
I have meet the samen issue and I have run ./install_corenlp to install Stanford CoreNLP,but I don't know how to  understand this: If you use Stanford CoreNLP, have the jars in your java CLASSPATH environment variable, or set the path programmatically with:
import drqa.tokenizers
drqa.tokenizers.set_default('corenlp_classpath', '/your/corenlp/classpath/*')

Thank you.

**Comment by ajfisch** [comment]
If you ran ./install_corenlp, then would have seen the instruction:

NOW RUN: `export CLASSPATH=$CLASSPATH:data/corenlp/*`

This adds the jars to your `CLASSPATH`. `CLASSPATH` is an environment variable that java uses to find classes to import, much like `PYTHONPATH` or the system `PATH`.

**Comment by liujinyan12** [comment]
Yes,I have done,but I still have the same issue.
My steps is as following:
I have installed Aanconda,python 3.6,Pytorch,then 
ljy@ubuntu:git clone https://github.com/facebookresearch/DrQA.git
ljy@ubuntu:cd DrQA; pip install -r requirements.txt; python setup.py develop
ljy@ubuntu:~/DrQA$ sudo bash install_corenlp.sh 

~/DrQA
Add to ~/.bashrc CLASSPATH (recommended)? [yes/no]: yes

*** NOW RUN: ***

export CLASSPATH=$CLASSPATH:data/corenlp/*

****************
ljy@ubuntu:~/DrQA$ python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from drqa.tokenizers import CoreNLPTokenizer
>>> tok = CoreNLPTokenizer()
Traceback (most recent call last):
  File "/home/ljy/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/ljy/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ljy/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/home/ljy/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/home/ljy/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/home/ljy/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/home/ljy/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f15e1507080>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'e-headless\r\nTry: sudo apt-get install <selected package>\r\n\x1b]0;ljy@ubuntu: ~/DrQA\x07ljy@ubuntu:~/DrQA$ '
before (last 100 chars): b'e-headless\r\nTry: sudo apt-get install <selected package>\r\n\x1b]0;ljy@ubuntu: ~/DrQA\x07ljy@ubuntu:~/DrQA$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 5051
child_fd: 6
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"
>>> 

Why I still had errors.Maybe I have other mistakes?
Thank you .

**Comment by liujinyan12** [comment]
I have solved this problem.
After I installed java 8,the error vanished.
Thank you .

**Comment by ajfisch** [comment]
Hi @tiru1930, has your issue been resolved? Note that in addition to the tips here, if you are using zsh instead of bash you will need to escape the `*` in your `CLASSPATH` env variable (see #2 )

**Comment by ajfisch** [comment]
Closing for lack of response. If the issue persists, feel free to reopen!
