### ISSUE TITLE
valid metric using F1 but disable either validate unofficial train/dev or both, validate official function yields different F1 score

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [facebookresearch/DrQA#147]
Is validate unofficial function on train/dev in reader/train.py will affect the outcome of F1 score in validate official function?

**Comment by ajfisch** [comment]
I don't quite understand your question.

Normal training uses the official SQuAD validation functions to compute the F1 score on the dev set. This is used for early stopping.

The unofficial evaluation does not compute the same score. If you use that for early stopping, you will likely choose a different model.

**Comment by jason1818** [comment]
@ajfisch thank you for your reply.

Based on my understanding, evaluate unofficial only compute exact_match score. However, when I try to comment out validate_unofficial function in train.py, the output model is different. When I check on the training log file, the F1 scores are different from previous model's log file trained without comment out validate_unofficial function.

**Comment by ajfisch** [comment]
Do you also comment out the `validate_unofficial` call on the training set? ([line 484](https://github.com/facebookresearch/DrQA/blob/master/scripts/reader/train.py#L484)). That's the only way I would see it being different. The reason there is that `validate_official` on the train set does random sampling in the data loader (to get 10k examples only) which would advance the state of the random number generator, and affect the ordering of subsequent batches.

I imagine that the differences in scores are quite small?

**Comment by jason1818** [comment]
Yes, I comment out validate_unofficial call on training set & development set.

Attached the log files below:

Train with validate_unofficial call
![no_disable_validate_unofficial](https://user-images.githubusercontent.com/39854319/41051217-0a4d77cc-69e8-11e8-8a04-3bb349b1e8d7.PNG)

Train without validate_unofficial call
![disable_validate_unofficial](https://user-images.githubusercontent.com/39854319/41051227-0f8a9fc6-69e8-11e8-9976-95a96a97acf3.PNG)

**Comment by ajfisch** [comment]
Looks indeed like just differences in SGD due to the state of the random number generator.

You have a small training and dev set. I imagine you'll get similar variance by just picking different values for `--random-seed`.
