### ISSUE TITLE
Need Help To train Model with new Context

### ISSUE THREAD

**Issue by Ssdmc** [facebookresearch/DrQA#149]
hy , it's great work 

i need some help to train the model for new Context , and i have some questions 
 
in my case  i've  context format like ( Context : {.......} , Question : {....} , {Answer : .......} )
in text file , 
my question is how to train model for this context ??? 
I read DOCUMENT READER , but i don't know how to start ! 
so grateful for help !

**Comment by ajfisch** [comment]
Please see how to train models in the reader [readme](https://github.com/facebookresearch/DrQA/blob/master/scripts/reader/README.md).
