### ISSUE TITLE
File size unexpectedly exceeded ZIP64

### ISSUE THREAD

**Issue by nooralahzadeh** [facebookresearch/DrQA#151]
I have this problem in saving tfidf model in retriever.utils.save_sparse_csr(filename, tfidf, metadata)
Any recomendation?

**Comment by ajfisch** [comment]
Seems like an open issue in numpy: https://github.com/numpy/numpy/issues/10776. How big is the file you are trying to save?

**Comment by ajfisch** [comment]
Closing for now. If the problem persists, feel free to reopen.
