### ISSUE TITLE
Illegal Instruction Occured before Entering RnnDocReader

### ISSUE THREAD

**Issue by haow85** [facebookresearch/DrQA#152]
When execute the line "score_s, score_e = self.network(*inputs)" in model.py.DocReader , drqa reported an illegal instruction error. It turns out self.network is an RnnDocReader object, so I added some debug printing in RnnDocReader. It turns out the program never entered the RnnDocReader.__init__() function. Any idea on how to resolve this issue ?

**Comment by ajfisch** [comment]
I need some basic information to get started.

- What platform are you running on?
- What version of pytorch?
- Have you modified the code?

**Comment by ajfisch** [comment]
Your modifications are likely the cause of the error. Make sure you are initializing everything correctly, in order. This line initializes the network: https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/model.py#L47.

**Comment by ajfisch** [comment]
Closing for now. If you still have a problem, feel free to reopen.
