### ISSUE TITLE
use the chinese  dataset have the problem,why?

### ISSUE THREAD

**Issue by hoogang** [facebookresearch/DrQA#159]
07/10/2018 02:15:09 PM: [ ---------------------------------------------------------------------------------------------------- ]
07/10/2018 02:15:09 PM: [ Starting training... ]
THCudaCheck FAIL file=/pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu line=231 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "scripts/reader/train.py", line 537, in <module>
    main(args)
  File "scripts/reader/train.py", line 477, in main
    train(args, train_loader, model, stats)
  File "scripts/reader/train.py", line 211, in train
    train_loss.update(*model.update(ex))
  File "/home/hugang/DrQA/drqa/reader/model.py", line 222, in update
    loss.backward()
  File "/home/hugang/.pyenv/versions/3.6.0/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/hugang/.pyenv/versions/3.6.0/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:231
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int

**Comment by bigsausage** [comment]
We use the Chinese dataset and preprocess.py runs well.Our data format stays the same with SquDa.We change only the data preprocess and tokenizer part.I wonder if it is our promblem or it's because of the model itself because i didn't do anything to the model.
Besides, i see you said that" I haven't tried updating DrQA to PyTorch 0.3 yet -- maybe there's something not backwards compatible or you have a corrupted build of some sort. I'll check in a bit." in a similar problem .Actually we are using PyTorch 0.3. Would it be the problem? Thanks a lot!

**Comment by ajfisch** [comment]
Looks like you have an invalid target index. Most likely your changes to the data preprocessing and tokenizing are wrong. You are providing a span index which is out of bounds.

**Comment by bigsausage** [comment]
Exactly.I changed the find_answer function in preprocess.py in order to match more answers but it seems that it got some problems in the BP(over the boundaries like you said). Now the promblem's fixed.Thanks a lot.
