### ISSUE TITLE
KeyError when training on SQuAD 2.0 dataset

### ISSUE THREAD

**Issue by zredlined** [facebookresearch/DrQA#166]
I'm trying to train a DrQA reader on the SQuAD 2.0 training and development sets, but it errors out after the first epoch, even with the --official-eval flag turned off.  The same script and approach completes successfully for the SQuAD 1.1 set. Any ideas about how to fix or support would be much appreciated. Thanks!

Error
-----

07/25/2018 09:33:47 PM: [ train: Epoch = 0 | iter = 2675/2690 | loss = 4.19 | elapsed time = 238.20 (s) ]
07/25/2018 09:33:48 PM: [ train: Epoch 0 done. Time for epoch = 239.33 (s) ]
07/25/2018 09:33:59 PM: [ train valid unofficial: Epoch = 0 | start = 50.66 | end = 56.24 | exact = 42.28 | examples = 10016 | valid time = 11.27 (s) ]
07/25/2018 09:34:07 PM: [ dev valid unofficial: Epoch = 0 | start = 29.44 | end = 31.40 | exact = 25.73 | examples = 11873 | valid time = 7.47 (s) ]
Traceback (most recent call last):
  File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 495, in main
    if result[args.valid_metric] > stats['best_valid']:
KeyError: 'f1'

Training parameters
------------------

Training parameters that I'm using below (please note this successfully trains for 1.1 dataset)
#TRAIN_VERSION="v1.1"
TRAIN_VERSION="v2.0"

time python scripts/reader/train.py \
  --tune-partial 1000 \
  --data-dir ./data/datasets \
  --embed-dir ./data/embeddings \
  --embedding-file glove.840B.300d.txt \
  --train-file SQuAD-$TRAIN_VERSION-train-processed-corenlp.txt \
  --dev-file SQuAD-$TRAIN_VERSION-dev-processed-corenlp.txt \
  --dev-json SQuAD-$TRAIN_VERSION-dev.json \
  --official-eval false 

Configuration
-------------

CONFIG:
{
    "batch_size": 32,
    "checkpoint": false,
    "concat_rnn_layers": true,
    "cuda": true,
    "data_dir": "./data/datasets",
    "data_workers": 5,
    "dev_file": "./data/datasets/SQuAD-v2.0-dev-processed-corenlp.txt",
    "dev_json": "./data/datasets/SQuAD-v2.0-dev.json",
    "display_iter": 25,
    "doc_layers": 3,
    "dropout_emb": 0.4,
    "dropout_rnn": 0.4,
    "dropout_rnn_output": true,
    "embed_dir": "./data/embeddings",
    "embedding_dim": 300,
    "embedding_file": "./data/embeddings/glove.840B.300d.txt",
    "expand_dictionary": false,
    "fix_embeddings": false,
    "gpu": -1,
    "grad_clipping": 10,
    "hidden_size": 128,
    "learning_rate": 0.1,
    "log_file": "/tmp/drqa-models/20180725-7019a2e5.txt",
    "max_len": 15,
    "model_dir": "/tmp/drqa-models/",
    "model_file": "/tmp/drqa-models/20180725-7019a2e5.mdl",
    "model_name": "20180725-7019a2e5",
    "model_type": "rnn",
    "momentum": 0,
    "no_cuda": false,
    "num_epochs": 40,
    "official_eval": false,
    "optimizer": "adamax",
    "parallel": false,
    "pretrained": "",
    "question_layers": 3,
    "question_merge": "self_attn",
    "random_seed": 1013,
    "restrict_vocab": true,
    "rnn_padding": false,
    "rnn_type": "lstm",
    "sort_by_len": true,
    "test_batch_size": 128,
    "train_file": "./data/datasets/SQuAD-v2.0-train-processed-corenlp.txt",
    "tune_partial": 1000,
    "uncased_doc": false,
    "uncased_question": false,
    "use_in_question": true,
    "use_lemma": true,
    "use_ner": true,
    "use_pos": true,
    "use_qemb": true,
    "use_tf": true,
    "valid_metric": "f1",
    "weight_decay": 0
} ]

**Comment by ajfisch** [comment]
If you use `--official-eval` as false, then you need to switch the `--valid-metric` to be `exact_match`. The unofficial evaluation doesn't compute the `f1` score.

**Comment by zredlined** [comment]
Works great, thanks!

**Comment by GhostAtom** [comment]
Hi @zredlined , did you modify the `scripts/reader/train.py` script for SQuAD 2.0 or it's working out of the box?
