### ISSUE TITLE
 ValueError max() arg is an empty sequence on SQuAD 2.0 dataset

### ISSUE THREAD

**Issue by zredlined** [facebookresearch/DrQA#167]
When I attempt to train using default settings I get the following error. I'd love to get this working so I can see f1 score for test. Any idea what's going on?

07/26/2018 11:43:11 PM: [ train: Epoch = 0 | iter = 2650/2690 | loss = 4.39 | elapsed time = 236.75 (s) ]
07/26/2018 11:43:13 PM: [ train: Epoch = 0 | iter = 2675/2690 | loss = 4.19 | elapsed time = 238.94 (s) ]
07/26/2018 11:43:14 PM: [ train: Epoch 0 done. Time for epoch = 240.06 (s) ]
07/26/2018 11:43:26 PM: [ train valid unofficial: Epoch = 0 | start = 50.66 | end = 56.24 | exact = 42.28 | examples = 10016 | valid time = 11.97 (s) ]
07/26/2018 11:43:33 PM: [ dev valid unofficial: Epoch = 0 | start = 29.44 | end = 31.40 | exact = 25.73 | examples = 11873 | valid time = 7.02 (s) ]
Traceback (most recent call last):
File "scripts/reader/train.py", line 542, in 
main(args)
File "scripts/reader/train.py", line 492, in main
dev_offsets, dev_texts, dev_answers)
File "scripts/reader/train.py", line 303, in validate_official
utils.exact_match_score, prediction, ground_truths))
File "/home/ubuntu/dev/python3/DrQA/drqa/reader/utils.py", line 232, in metric_max_over_ground_truths
return max(scores_for_ground_truths)
ValueError: max() arg is an empty sequence

Training parameters
------------------
Training parameters that I'm using below (please note this successfully trains for 1.1 dataset)

#TRAIN_VERSION="v1.1"
TRAIN_VERSION="v2.0"

time python scripts/reader/train.py 
--tune-partial 1000 
--data-dir ./data/datasets 
--embed-dir ./data/embeddings 
--embedding-file glove.840B.300d.txt 
--train-file SQuAD-$TRAIN_VERSION-train-processed-corenlp.txt 
--dev-file SQuAD-$TRAIN_VERSION-dev-processed-corenlp.txt 
--dev-json SQuAD-$TRAIN_VERSION-dev.json 

Configuration
-------------
CONFIG:
{
"batch_size": 32,
"checkpoint": false,
"concat_rnn_layers": true,
"cuda": true,
"data_dir": "./data/datasets",
"data_workers": 5,
"dev_file": "./data/datasets/SQuAD-v2.0-dev-processed-corenlp.txt",
"dev_json": "./data/datasets/SQuAD-v2.0-dev.json",
"display_iter": 25,
"doc_layers": 3,
"dropout_emb": 0.4,
"dropout_rnn": 0.4,
"dropout_rnn_output": true,
"embed_dir": "./data/embeddings",
"embedding_dim": 300,
"embedding_file": "./data/embeddings/glove.840B.300d.txt",
"expand_dictionary": false,
"fix_embeddings": false,
"gpu": -1,
"grad_clipping": 10,
"hidden_size": 128,
"learning_rate": 0.1,
"log_file": "/tmp/drqa-models/20180725-7019a2e5.txt",
"max_len": 15,
"model_dir": "/tmp/drqa-models/",
"model_file": "/tmp/drqa-models/20180725-7019a2e5.mdl",
"model_name": "20180725-7019a2e5",
"model_type": "rnn",
"momentum": 0,
"no_cuda": false,
"num_epochs": 40,
"official_eval": true,
"optimizer": "adamax",
"parallel": false,
"pretrained": "",
"question_layers": 3,
"question_merge": "self_attn",
"random_seed": 1013,
"restrict_vocab": true,
"rnn_padding": false,
"rnn_type": "lstm",
"sort_by_len": true,
"test_batch_size": 128,
"train_file": "./data/datasets/SQuAD-v2.0-train-processed-corenlp.txt",
"tune_partial": 1000,
"uncased_doc": false,
"uncased_question": false,
"use_in_question": true,
"use_lemma": true,
"use_ner": true,
"use_pos": true,
"use_qemb": true,
"use_tf": true,
"valid_metric": "f1",
"weight_decay": 0
} ]

**Comment by krutikabapat** [comment]
I am facing the same issue. Is this issue resolved by anyone? Please help!
