### ISSUE TITLE
Wrong answers

### ISSUE THREAD

**Issue by basque21** [facebookresearch/DrQA#173]
Hi, it's a great and amazing work, but is it common to answer things like "What is the diameter of the sun" -> "3cm" (a text says that "if the Sun-Neptune distance is scaled to 100 m-s...."), or "what is the color of the sky" -> "black", and the answer is a part of a text of the moon's sky... I mean, it can't be used in a chatbot to answer general knowledge questions, can it?

Thx

**Comment by ajfisch** [comment]
Yes, this is expected. To use it in a chatbot I'd recommend restricting the domain (types of questions asked, and supporting text used).
