### ISSUE TITLE
Adjusting for German Language

### ISSUE THREAD

**Issue by ArlindNocaj** [facebookresearch/DrQA#174]
Hi DrQA team, 

really great implementation. Very easy to use and understand!

Could you give some hints at which points one has to adjust for Language to support another language for QA? (Tokenizer,Lemma, NER, POS?)

Thnx for your feedback.

**Comment by ajfisch** [comment]
Yes, the easy fixes are using a language specific tokenizer with appropriate lemma, NER, POS tools. This is all in the tokenizers directory. 

The harder fix is either training a multilingual model (perhaps an easy thing to try for at least syntactically similar languages is using aligned bilingual embeddings such as from [MUSE](https://github.com/facebookresearch/MUSE)) or getting training data in the language of your choice.
