### ISSUE TITLE
reader with file candidate

### ISSUE THREAD

**Issue by basque21** [facebookresearch/DrQA#175]
Hi, is it possible to use the `reader.interactive.py` to predict an answer feeding a wikipedia article title name instead of a text? say, `process('List of Presidents of the United States', 'who was the first president of the United States?')`
Thx

**Comment by ajfisch** [comment]
It's pretty easy to extend `interactive.py` to do this. Simply use the `DocDB` like so:

```python
db = DocDB()
doc_text = db.get_doc_text('Barack Obama')
process(doc_text, question)
```

Note that "List of..." articles were excluded from the default Wikipedia dump.
