### ISSUE TITLE
continue download.sh without download data.tar

### ISSUE THREAD

**Issue by soroushmbk** [facebookresearch/DrQA#178]
i ran download.sh and downloaded data.tar and also extracted datasets but i got an error while getting squad data.
i fix the problem. now i want to rerun download.sh, but code try to download data.tar again!

what can i do to run download.sh without re download data.tar but running next steps.

**Comment by ajfisch** [comment]
Hi,

You can just comment out [lines 20-27](https://github.com/facebookresearch/DrQA/blob/master/download.sh#L20-L27).
