### ISSUE TITLE
document retrieval

### ISSUE THREAD

**Issue by demeiyan** [facebookresearch/DrQA#179]
Hi Adam,

Which paper  the document retrieval is based on . I want to read it then know how to implement.

Thanks.

**Comment by ajfisch** [comment]
It's based on TF-IDF, which is a topic found in any introductory IR/NLP text book. The [Jurafsky & Martin](https://web.stanford.edu/~jurafsky/slp3/ed3book.pdf) textbook is a good resource (section 6.5 talks about TF-IDF).
