### ISSUE TITLE
Error running downlaod.sh

### ISSUE THREAD

**Issue by RitwikGopi** [facebookresearch/DrQA#18]
On running download.sh I am getting the following error. Any insight into this?
```DRQA_DATA not set; downloading to default path ('data').
data/
data/datasets/
data/datasets/CuratedTrec-test.txt
data/datasets/CuratedTrec-train.txt
data/datasets/WikiMovies-entities.txt
data/datasets/WikiMovies-test.txt
data/datasets/WikiMovies-train.txt
data/reader/
data/reader/multitask.mdl
data/reader/single.mdl
data/wikipedia/
data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by ajfisch** [comment]
Hm, I'm not sure, but there are a couple of things you might try:

- Are you using OSX/Linux?
- Try using gnu-tar? (if not already)
- Perhaps the archive got corrupted during download, `rm -rf data` and `rm data.tar.gz` and re-download?

**Comment by RitwikGopi** [comment]
I am using linux. I will try out and comment again.

**Comment by RitwikGopi** [comment]
I was able to successfully run this script on a different machine. Before while I was downloading the tar I had to resume the download since there was a network error in between. I think that is what caused the problem.

**Comment by ajfisch** [comment]
Glad the issue was resolved. Points to a corrupted download then.
