### ISSUE TITLE
TF-IDF similarity

### ISSUE THREAD

**Issue by yairf11** [facebookresearch/DrQA#186]
Hi,

I went through the tf-idf retriever code, and it seems as though you are not using the normalized tf-idf vectors, or in other words you are calculating the dot product between a query and a document but not the cosine similarity.
Am I wrong? If not, what is the reason for doing so?

Thanks,
Yair

**Comment by ajfisch** [comment]
We are calculating the TF-IDF score (specifically with a probabilistic inverse document frequency term). It's different from cosine.

**Comment by ajfisch** [comment]
Sorry, misread your question -- we weight it each vector with [tf-idf](https://github.com/facebookresearch/DrQA/blob/master/drqa/retriever/tfidf_doc_ranker.py#L90). We could then renorm it to unit length to get a cosine score, but don't. Taking the dot product between two the two already term-weighted vectors worked well.

**Comment by yairf11** [comment]
Great, Thanks!
I actually tested this myself on a similar dataset, and indeed the similarity from the dot product got better results than when normalizing to get a cosine score.
