### ISSUE TITLE
Sequence of actions to replicate results

### ISSUE THREAD

**Issue by hrahmati** [facebookresearch/DrQA#187]
I'm trying to retrain and rerun the whole system from 0 to 100 on my own and replicate the results, but I really got confused while reading READMEs. 
Would you give me a brief walkthrough about the sequence of scripts that need to run so I can fulfill this task? 
Actually, first I want to do it on a small scale set of data and then switch to whole SQuAD, WikiMovies, WebQuestions and ... so I kinda need to know the exact sequence.
And would you also let me know what is the minimum required Ram, CPU, ... for DrQA to be trained and run efficiently?

**Comment by ajfisch** [comment]
I'd suggest first replicating SQuAD results (Reader README). Then build the retriever (Retriever README). Then test the pipeline. Then generate distant supervision (distant supervision README). Then retrain. Then test again.
