### ISSUE TITLE
CC-BY-NC

### ISSUE THREAD

**Issue by chikiuso** [facebookresearch/DrQA#19]
Any plan or chance I could use it for commercial application? thanks.

**Comment by ajfisch** [comment]
TLDR; No.

The current release is primarily for researchers/students to evaluate and to integrate DrQA in research projects. For this CC-BY-NC (which prohibits commercial use) is enough. In the future, however, we may relax the license.

**Comment by ajfisch** [comment]
Hi, the license is now expanded to a BSD.
