### ISSUE TITLE
Using corenlp

### ISSUE THREAD

**Issue by voquocbang** [facebookresearch/DrQA#193]
I was trying to run the example below after installing corenlp "./install_corenlp.sh"

from drqa.tokenizers import CoreNLPTokenizer
tok = CoreNLPTokenizer()
tok.tokenize('hello world').words()  # Should complete immediately

Annd I got this error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/DrQA/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/root/anaconda3/envs/DrQA/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 33, in __init__
    self._launch()
  File "/home/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 61, in _launch
    self.corenlp.expect_exact('NLP>', searchwindowsize=100)
  File "/root/anaconda3/envs/DrQA/lib/python3.6/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/root/anaconda3/envs/DrQA/lib/python3.6/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/root/anaconda3/envs/DrQA/lib/python3.6/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f47be6a6dd8>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b'rQA# bash: java: command not found\r\n\x1b]0;root@2106d23e44c7: /home/DrQA\x07root@2106d23e44c7:/home/DrQA# '
before (last 100 chars): b'rQA# bash: java: command not found\r\n\x1b]0;root@2106d23e44c7: /home/DrQA\x07root@2106d23e44c7:/home/DrQA# '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3313
child_fd: 7
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"
I don't understand this problem so I need some help. Many thanks.

**Comment by Planck35** [comment]
I also encounter this problem.

I find that if you set the annotators to `'pos', 'lemma', 'ner'`. It will pop out this `Timeout error`

If you set annotators to `'pos', 'lemma'` or `'pos'`, there is no problem.

So I use the latest [CoreNLPTokenizer](http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip) from Stanford.

It works.

P.S. The start index found code has bugs
```Python
        output = self.corenlp.before
        start = output.find(b'{"sentences":')
        output = json.loads(output[start:].decode('utf-8'))
```
There is one more space between `'{'` and 'sentences'

I think you can just skip finding `start`, like this
```Python
        output = self.corenlp.before
        output = json.loads(output.decode('utf-8'))
```

**Comment by jscheidtmann** [comment]
Check your CLASSPATH environment variable. 

In `drqa/tokenizers/corenlp_tokenizers.py`, add a `print(' '.join(cmd))` after the cmd-variable is set in `_launch`. This will print the exact java command line that is executed multiple times during startup. Make sure this does not give an error.

**Comment by voquocbang** [comment]
Just find out that I got a memory overflow. I'd configured the setting on cloud and all worked fine.
