### ISSUE TITLE
is it possible to use alternative articles? instead of wikipedia

### ISSUE THREAD

**Issue by sjhddh** [facebookresearch/DrQA#20]
Just trying to see if this model can be transferred into other domain.

**Comment by ajfisch** [comment]
Yes, of course! See the retriever README for explicit instructions on how to do this for any corpus. Note that if the domain is quite different you would do well to build more training data (perhaps with distant supervision).

**Comment by sjhddh** [comment]
Hi Adam, which doc are you referring to? I cannot see a README in retriver folder.

**Comment by ajfisch** [comment]
https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/README.md
