### ISSUE TITLE
Character Limit when trying to input my own corpus of text

### ISSUE THREAD

**Issue by NatCusack** [facebookresearch/DrQA#202]
Hi!
I'm trying to get DrQA working on my own text corpus and I have run into an problem.
Long story short I am processing a book with 181 pages and treating each page as a document (I did this because each page covers a different topic).
ie my json file looks like this:
```
{"id": "page1", "text": "-page1 text-"}
.....
{"id": "pageN", "text": "-pageN text-"}
```

when using build_db.py build the SQlite database I get greeted with this error : `json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 1 (char 4094)`

I think this is because there is a limit of 4093 characters per line in json (including the tagging, brackets and all that stuff.)
When I remove lines > 4093 chars, there is no error and the db is built.

Is there anyway to increase the limit, rather than splitting my book into sentences/paragraphs to meet the criteria of a max of 4093 characters. I'm not sure but I imagine that if i split by sentences/ paragraphs there would be a contextual problem when it comes to the machine comprehension step.

Thanks in advance for any help or interest!

**Comment by ajfisch** [comment]
Are you sure there isn't a problem in your JSON encoding? Are you encoding it with proper escaping, i.e. via `json.dumps`? AFAIK there isn't a limit in the value field for json. I.e.

```bash
python -c 'import json; e = json.dumps({"A": "A" * 100000}); d = json.loads(e);'
```
Removing lines with > 4093 would also remove any offending lines you have.

**Comment by NatCusack** [comment]
Funny I thought I was but did the same process just to test it again and it work perfectly. Thanks for your speedy response!

**Comment by krutikabapat** [comment]
@NatCusack How did you finally solve your problem? I am facing the same issue. Urgent help is required :'( I am working on university project.
