### ISSUE TITLE
Error with python after pytorch 1.0 update

### ISSUE THREAD

**Issue by vrajpatel231296** [facebookresearch/DrQA#205]
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

**Comment by ajfisch** [comment]
Make sure your pytorch 1.0 is installed correctly, and if you're using cuda, you have the right version of cuda installed too.

**Comment by qchenclaire** [comment]
> python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
> Segmentation fault (core dumped)

Hi have you solved this yet? I have the same problem, with ubuntu 18.04, cuda 10.1. I built Pytorch from source with LibTorch, following instructions here: https://michhar.github.io/how-i-built-pytorch-gpu/ I built it successfully but I have no idea why it has the same error as yours when I try to import torch.
