### ISSUE TITLE
I cannot download the data and pretrained model

### ISSUE THREAD

**Issue by fooSynaptic** [facebookresearch/DrQA#208]
`failed: nodename nor servname provided, or not known.
`

**Comment by sumanyumuku98** [comment]
Can you specify the steps to recreate the error?
I was able to download the pretrained model and data following the documentation.
First:
~~~python
git clone https://github.com/facebookresearch/DrQA.git
cd DrQA; pip install -r requirements.txt; python setup.py develop
~~~
And then:
~~~
./download.sh
~~~

**Comment by fooSynaptic** [comment]
the exception was solved, it's the network issue. thanks
