### ISSUE TITLE
Doc Score vs Answer Score

### ISSUE THREAD

**Issue by impulsecorp** [facebookresearch/DrQA#209]
I understand what the Answer Score is, like how it is used to rank the top 10 DrQA answers to a question. But what is the Doc Score? I understand the Doc is the name of the text I am trying to get the answer from, but how does that score help me predict which answer is best or how good the answer is? Is it the TF-IDF score of the Question vs the Doc text?

**Comment by ajfisch** [comment]
Yes, it’s the TFIDF value.
