### ISSUE TITLE
Answer Span Question

### ISSUE THREAD

**Issue by impulsecorp** [facebookresearch/DrQA#210]
Is there are way for DrQA to give me the specific sentence in the document context where it found the answer? Sometimes the context will contain multiple mentions of the DrQA answer and right now I have no way of knowing exactly what part of the document it got that answer from.

**Comment by ajfisch** [comment]
Yep! Just specify `return_context=True` to the pipeline. Like in the [interactive script](https://github.com/facebookresearch/DrQA/blob/master/scripts/pipeline/interactive.py#L80-L82).

For every prediction it will return the paragraph text along with the predicted answer span's start and end character offsets. These are in each predictions `context` field, sub-indexed via `text`, `start`, and `end`.
