### ISSUE TITLE
Is it possible to train reader on new DROP dataset?

### ISSUE THREAD

**Issue by NatCusack** [facebookresearch/DrQA#212]
Hi! I was wondering if it was possible to train the reader with the new **D**iscrete **R**easoning **O**ver **P**aragraphs that Allen Ai recently released  : https://allennlp.org/drop
Is there any intent to add this to the model in the future?
Is it possible to train it with the current model?

Thanks in advance!
Nathan

**Comment by ajfisch** [comment]
No plans for this repo.
