### ISSUE TITLE
Is dynamic graph feature used actively in RC Model?

### ISSUE THREAD

**Issue by anand-ar** [facebookresearch/DrQA#216]
Are you using this feature in RC model? I assume every epoch the graph is created by pytorch but looks like it is the same graph every time?

**Comment by ajfisch** [comment]
Unsure of the question. PyTorch is dynamic, it's not like Tensorflow. Easy to implement as a static graph however. This is basically DrQA: https://github.com/google-research/language/blob/master/language/question_answering/models/nq_short_pipeline_model.py
