### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by magnificGH** [facebookresearch/DrQA#22]
when I running interactive.py ,there are some error:
08/04/2017 09:36:03 AM: [ CUDA enabled (GPU -1) ]
08/04/2017 09:36:03 AM: [ Initializing pipeline... ]
08/04/2017 09:36:03 AM: [ Initializing document ranker... ]
08/04/2017 09:36:03 AM: [ Loading /home/li/software/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
08/04/2017 09:42:02 AM: [ Initializing model... ]
08/04/2017 09:42:04 AM: [ Loading model /home/li/software/DrQA/data/reader/multitask.mdl ]
08/04/2017 09:43:42 AM: [ Initializing tokenizers and document retrievers... ]
Traceback (most recent call last):
  File "interactive.py", line 70, in <module>
    tokenizer=args.tokenizer
  File "/home/li/software/DrQA/drqa/pipeline/drqa.py", line 140, in __init__
    initargs=(tok_class, tok_opts, db_class, db_opts, fixed_candidates)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
I would appreciate it if you could give me some advice,thanks

**Comment by ajfisch** [comment]
What kind of machine are you running on? (E.g RAM/cores?)

**Comment by RitwikGopi** [comment]
Am also getting the same error. Using a Linux machine. 24 GB RAM, 8 core machine.

**Comment by ajfisch** [comment]
I am not sure, but perhaps it might be that you have over-commit disabled on your machines?

What is the value of `cat /proc/sys/vm/overcommit_memory`? If it is 2, try `echo 1 >  /proc/sys/vm/overcommit_memory` or `echo 0 /proc/sys/vm/overcommit_memory`

**Comment by jimmy702** [comment]
I am also getting the same error, and already check my overcommit_memory, It is 0.
# cat /proc/sys/vm/overcommit_memory
0

**Comment by RitwikGopi** [comment]
For me too it is zero.

**Comment by RitwikGopi** [comment]
`echo 1 > /proc/sys/vm/overcommit_memory`
This did the trick for me. Just like @ajfisch suggested. Keeping it 0 might not be working because of the below reason. 
```
You may workaround the above issue, by changing the value in /proc/sys/vm/overcommit_memory to 1 or 0 if it is set to 2 in the file. 

overcommit_memory: This value contains a flag that enables memory overcommitment.
- When this flag is 0, the kernel attempts to estimate the amount of free memory left when userspace requests more memory.
- When this flag is 1, the kernel pretends there is always enough memory until it actually runs out.
- When this flag is 2, the kernel uses a "never overcommit" policy that attempts to prevent any overcommit of memory.

Note: In case, the value is 1 or 0, then you have to definitely consider options to increase RAM / SWAP space to get back to a setting of 2 since that's 

```
Link to original post `https://discuss.pivotal.io/hc/en-us/articles/201083147-Pivotal-HDB-Initialization-or-reload-fails-with-OSError-Errno-12-Cannot-allocate-memory`

**Comment by ajfisch** [comment]
Glad to hear it is working for you now! I might try to investigate how to reduce the amount of virtual memory allocated to make non-overcommit enabled systems happy, but I don't think that I'll get around to it anytime soon.

In the meantime, @magnificGH @jimmy702  try explicitly enabling overcommit as @RitwikGopi has done.
