### ISSUE TITLE
elasticsearch integration document

### ISSUE THREAD

**Issue by jmlongriver** [facebookresearch/DrQA#220]
Hi, 

I am wondering if there is a readme about how to integrate elasticsearch into the tool, thanks!

**Comment by Dobatymo** [comment]
You simply have to change the config to something like this:
```python
    ranker_config={
        'class': ElasticDocRanker,
        'options': {
            'elastic_fields': ['text'],
            'elastic_field_doc_name': 'title',
            'elastic_field_content': 'text',
            'elastic_index': 'wiki-articles'
        }
    },```

**Comment by ajfisch** [comment]
Cleaning up issues. There is no README -- see above. Feel free to pull request with instructions.
