### ISSUE TITLE
hangs up at "Reading paragraphs"

### ISSUE THREAD

**Issue by red8top** [facebookresearch/DrQA#221]
I'm trying to run a default example, I get no errors but also no output - am I missing something?
predict also seems to just hangup 

>>> process('How many counties are in the United States?')
05/16/2019 11:25:06 AM: [ Processing 1 queries... ]
05/16/2019 11:25:06 AM: [ Retrieving top 5 docs... ]
05/16/2019 11:25:10 AM: [ Reading 406 paragraphs... ]

**Comment by rajo19** [comment]
Did you solve this problem because I am facing the same error?

**Comment by red8top** [comment]
No I'm still totally stuck!  I'm also seeing basically no load so it's like the java instances are just sitting doing nothing?
This was trying the pipeline examples, today I was going to start working through the component examples to see if I can narrow it to one part of the pipeline

**Comment by rajo19** [comment]
Oh.. I am also stuck.. In my case, it was running before 3 to 4 days but now it is not working. I reinstalled the DrQA model but still nothing. If you get some solution please post it.

**Comment by kajo404** [comment]
Hi, I had the same issue but was able to solve it by downgrading some libraries. What version of pytorch are you running?

**Comment by rajo19** [comment]
Hi, my pytorch version is 1.1.0. Can you tell in which version did you run it?

**Comment by kajo404** [comment]
> DrQA requires Linux/OSX and Python 3.5 or higher. It also requires installing PyTorch version 1.0. Its other dependencies are listed in requirements.txt. CUDA is strongly recommended for speed, but not necessary.

This is from the README. Try downgrading to 1.0.x and see if it works. I also downgraded numpy to 1.16.2

**Comment by red8top** [comment]
Great catch, that worked!  I had numpy downgraded cuz at least that throws an error.
Thanks for the help.

Any idea if there is much reason to try and get this working on more current pytorch, or convert it to tensorflow, or resources on doing that?

**Comment by ajfisch** [comment]
It's on my wishlist :).

**Comment by red8top** [comment]
I suppose that means it'd be intensive?  
I'm very amateur but I AM scrappy and a fast learner, so if it's at all possible to muddle through I might make it..?
Any tips welcome but in any case, feel free to close this out, it's looking good!

**Comment by Dobatymo** [comment]
To be clear for future readers: Torch 1.0.1 works, Torch 1.1.0 does not.

**Comment by krutikabapat** [comment]
@red8top @Dobatymo I am facing exactly the same error. I have already tried downgrading the environments but, it does not work for me. My system already meets the system requirements. Bu the process just hangs up:
```
 process("When was American software incorporated?", candidates="None", top_n=1, n_docs=1)
04/14/2020 12:31:51 AM: [ Processing 1 queries... ]
04/14/2020 12:31:51 AM: [ Processing 1 queries... ]
04/14/2020 12:31:51 AM: [ Retrieving top 1 docs... ]
04/14/2020 12:31:51 AM: [ Retrieving top 1 docs... ]
[137.55464521]
04/14/2020 12:31:51 AM: [ Reading 1 paragraphs... ]
04/14/2020 12:31:51 AM: [ Reading 1 paragraphs... ]
```
Any help would be highly appreciated. Thanks!

**Comment by gud111** [comment]
Thir documentation is incomplete and after much googling, it looks like we need older versions of spacy/numpy/torch/scipy. After much trying the following seem to work for me: 
torch              1.0.0
torchvision        0.2.1
scipy              1.4.0
spacy              2.1.0
numpy              1.16.2
