### ISSUE TITLE
Different Reader Model

### ISSUE THREAD

**Issue by rajo19** [facebookresearch/DrQA#222]
I am planning to use a different reader model on this Model. Can anyone please tell how can I integrate the retriever model here to the reader model that I am planing to use?

**Comment by ajfisch** [comment]
Just make sure you follow the same API as the DocReader (i.e. implement `.predict`) and stick it in here: https://github.com/facebookresearch/DrQA/blob/master/drqa/pipeline/drqa.py#L113. Might want to modify remove the other calls to the reader as well (like expanding the dictionary).
