### ISSUE TITLE
DrQA unable to fetch information when a question is sent via the process(...) while using pipeline's interactive.py script

### ISSUE THREAD

**Issue by SmritiSatyan** [facebookresearch/DrQA#230]
Hello, I am working on DrQA and trying to run the interactive.py present in pipeline folder of scripts folder. Whenever I enter a question to the process(...), it gives the below warning- Not sure where I need to change mask type. 
I also saw this https://github.com/jiesutd/NCRFpp/issues/137, but not sure where I need to change from byte to bool. 
Any suggestions would be highly appreciated. 
My torch version is 1.3.1 (If that is required)

```
11/18/2019 11:48:53 AM: [ Processing 1 queries... ]
11/18/2019 11:48:53 AM: [ Retrieving top 5 docs... ]
11/18/2019 11:48:54 AM: [ Reading 111 paragraphs... ]
/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead
```

**Comment by SmritiSatyan** [comment]
There were 2 reasons- 
1. I had a higher version of Pytorch running on my system. Installed the Pytorch version 1.0.0 with CUDA (so that answers are fetched quickly)
2. I had less memory (was getting MemoryError) and numpy version had to be downgraded to 1.16.2

**Comment by anushkmittal** [comment]
@SmritiSatyan how much memory did you need? and how much was your response time to queries?

**Comment by anushkmittal** [comment]
note to future self / other people: I solved this problem then forgot how to solve it. to save more 12+ hrs of frustration, #221 solves it. 

specifically, downgrade torch to 1.0.x and numpy to 1.16.2
