### ISSUE TITLE
look for idea and suggestion on port it to support big character set language like  Chinese or Japanese?

### ISSUE THREAD

**Issue by loveJasmine** [facebookresearch/DrQA#24]

**Comment by ajfisch** [comment]
Hi @loveJasmine,

I apologize, but as mentioned in #16 and #10 DrQA only supports English, and I'd like to keep the Issues questions here related to the current implementation and training.

In #16 and #10 I gave some ideas on how you might proceed in adapting a DrQA model to a new language.
