### ISSUE TITLE
Any plans for supporting 3.7+

### ISSUE THREAD

**Issue by ebal5** [facebookresearch/DrQA#246]
according to #227 or #35 , there is no support for Python 3.7+ I think.
Today (2020-04-17), I tried to use DrQA with 3.8, I found this problem.

Does this project has any plans for support Python 3.7+? 
In other words,  is there any plans for updating dependency of pexpect?

**Comment by hughperkins** [comment]
You can use `--tokenizer regexp`, to workaround the pexpect issue. (just install the latest version of pexpect, since it wont be used if you dont use stanford core nlp tokenizer)

**Comment by hughperkins** [comment]
(otherwise, you'd need to upgrade corenlp_tokenizer.py to the latest stanfordcorenlp recommended usage pattern)

**Comment by ebal5** [comment]
Thanks a lot.
