### ISSUE TITLE
Distant Supervision

### ISSUE THREAD

**Issue by joeattueyi** [facebookresearch/DrQA#28]
Hi,
Love your work, would like to know more on getting Distant Supervision to work, especially specifics on how to generate  and train on distantly supervised data.
Thanks,
Joe

**Comment by ajfisch** [comment]
Certainly. Scripts for generating the DS data are in scripts/distant. I will add a README for this shortly.

**Comment by cdjhz** [comment]
Can you provide more detail on how to implement distant supervision to build those QA datasets?  Many thanks!

**Comment by xllg** [comment]
I also want you provide more detail on how to implement distant supervision to build those QA Datasets. Many thanks!

**Comment by yangzw** [comment]
@ajfisch  I also don't know how to run generate.py in scripts/distant. Can you add a README for this?

**Comment by etown** [comment]
@ajfisch Would love a readme :-) thanks for all your work!

**Comment by ajfisch** [comment]
Sorry for the delay. I have added a readme (#72). Hope it is helpful!
