### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by romanegloo** [facebookresearch/DrQA#32]
Hi. First of all, thanks for sharing this project. I am actually learning a lot from it.

I guess memory is a big problem when dealing with a large document collection. I was trying to run it on pubmed corpus which has +800k documents.

When running the script to build tfidf (scripts/retriever/build_tfidf.py), it gives me an MemoryError as below:
```
Traceback (most recent call last):
  File "code/DrQA/scripts/retriever/build_tfidf.py", line 183, in <module>
    args, 'sqlite', {'db_path': args.db_path}
  File "code/DrQA/scripts/retriever/build_tfidf.py", line 123, in get_count_matrix
  File "/usr/local/lib/python3.5/dist-packages/scipy/sparse/compressed.py", line 51, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/usr/local/lib/python3.5/dist-packages/scipy/sparse/coo.py", line 149, in __init__
    self.row = np.array(row, copy=copy, dtype=idx_dtype)
MemoryError
```
I've tried to reduce the size of dtype with no success. It either fails at sp.csr_matrix() or count_matrix.sum_duplicates(). Is there a way to properly handle this issue?

I think I have plenty of memory space, but not sure about the count matrix.
>> cat /proc/meminfo
MemTotal:       131914996 kB
MemFree:        56948712 kB
MemAvailable:   69331336 kB

**Comment by ajfisch** [comment]
Building the tfidf matrix does consume quite a bit of memory (especially storing the data in python lists before converting to the scipy sparse representation. Memory usage will be max at `sp.csr_matrix() ` as it is storing both the data and allocating the scipy sparse matrix. I'm suprised that `sum_duplicates` is failing... that should be in-place. Maybe try adding `del data, row, col` before that. 

What does `htop` or `top` say while you're running `build_tfidf.py`? Can you see that you are indeed running out of RAM?

FWIW building the tfidf matrices for Wikipedia (which is 5M documents) took over 100GB of RAM (once in scipy goes to ~15GB).

As it is written now, `build_tfidf` emphasizes speed over memory usage, so you might be able to rewrite parts of it to fit in your memory constraints.

**Comment by romanegloo** [comment]
Thanks for your response.
With my corpus, it takes more than 150GB of RAM. At first, I was thinking of setting smaller hash_size, but 2^24 seems reasonable here. This [link](https://stackoverflow.com/questions/25145552/tfidf-for-large-dataset) from SO discusses about the same issue.
People suggests an iterative way of computing tfidf, or using a smaller corpus for training purpose. 
I've decided to use the latter.
