### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when building the TF-IDF N-grams

### ISSUE THREAD

**Issue by canguezelhan** [facebookresearch/DrQA#34]
When I want to build the TF-IDF N-grams using `build_tfidf.py`, I get this weird error. 

    (py3) C:\Users\cguzelha\PycharmProjects\DrQA>python scripts\retriever\build_tfidf.py data\manuals.db data\ --tokenizer spacy --num-workers 1
    09/01/2017 01:59:27 PM: [ Counting words... ]
    09/01/2017 01:59:27 PM: [ Mapping... ]
    09/01/2017 01:59:27 PM: [ -------------------------Batch 1/10------------------------- ]
    multiprocessing.pool.RemoteTraceback:
    """
    Traceback (most recent call last):
      File "C:\Users\cguzelha\AppData\Local\Continuum\Anaconda3\envs\py3\lib\multiprocessing\pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "C:\Users\cguzelha\PycharmProjects\DrQA\scripts\retriever\build_tfidf.py", line 81, in count
        col.extend([DOC2IDX[doc_id]] * len(counts))
    TypeError: 'NoneType' object is not subscriptable
    """

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "scripts\retriever\build_tfidf.py", line 183, in <module>
        args, 'sqlite', {'db_path': args.db_path}
      File "scripts\retriever\build_tfidf.py", line 114, in get_count_matrix
        for b_row, b_col, b_data in workers.imap_unordered(_count, batch):
      File "C:\Users\cguzelha\AppData\Local\Continuum\Anaconda3\envs\py3\lib\multiprocessing\pool.py", line 735, in next
        raise value
    TypeError: 'NoneType' object is not subscriptable

When I print the type of `DOC2IDX` in `get_count_matrix`, it is still a dictionary. However, when I print it again in `count`, it becomes `NoneType`. The input database `manuals.db` is built using `build_db.py`.

**Comment by ajfisch** [comment]
It looks like you're using Windows. DrQA only supports Linux/Unix. On Unix-like systems `multiprocessing` uses `fork` which allows the children to inherit the global variables of the parent. DrQA makes use of this. In Windows, this sharing of memory needs to be done explicitly.

**Comment by DipayanAwsm** [comment]
hi can you suggest how to do that memory sharing in windows
