### ISSUE TITLE
./download.sh error with 'Connection reset by peer'

### ISSUE THREAD

**Issue by fisherwangcn** [facebookresearch/DrQA#35]
Awesome project! I really want to try. But error occured when I run ./download.sh :

` 45800K .......... .......... .......... .......... ..........  0% 14.3K 4d1h
 45850K .......... .......... .......... .......... ..........  0% 14.3K 4d1h
 45900K .......... .......... .......... .......... ..........  0% 26.2K 4d1h
 45950K .......... .......... .......... .......... ..........  0% 1.90K 4d4h
 46000K .......... .......... .......... .......... ..........  0% 2.60K 4d6h
 46050K .......... .......... .......... .......... ..........  0% 3.50K 4d7h
 46100K .......... .......... .......... .......... ..........  0% 4.33K 4d8h
 46150K ...                                                     0% 70.2M=15m8s

2017-09-03 13:18:44 (20.9 KB/s) - Read error at byte 47261019/8104538193 (Connection reset by peer). `

My net Enviroment is in China. Could you provide another way to get the train data? 
Thank u!

**Comment by ajfisch** [comment]
It looks like an issue with your internet connection. I am not familiar with connectivity in China, perhaps you will need to be behind a VPN?

**Comment by fisherwangcn** [comment]
Sadness for Chinese developer... The network's speed is as slow as a snail.  I have got the dataSet. I prepare to upload the data for persons who has no VPN. I would to show the data url below this chat. Wait for my news.
Thank u again. Best wishes!

**Comment by fisherwangcn** [comment]
Hi ! I have upload the "data.tar.gz" to BaiduNetdisk for Chinese. Here is the url:
"http://pan.baidu.com/s/1i4Jksq5"

You also can wget it on Linux , as : 
wget -c -O data.tar.gz "https://d.pcs.baidu.com/file/ae72f77054d0323296fd5aadb92b4f7e?fid=3350193642-250528-515376104476194&time=1504538012&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-tkP4X9rFwV0XhDv65iw1EIDdSQ4%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=5727878957661089162&dp-callid=0&r=359987858"

Good luck!

**Comment by ajfisch** [comment]
Thanks!
