### ISSUE TITLE
Could I have a sample file of json text when calling predict.py?

### ISSUE THREAD

**Issue by chikiuso** [facebookresearch/DrQA#38]
Could I have a sample file of json text when calling predict.py (for batch processing)? I try following the format on readme document but failed, thanks.

**Comment by ajfisch** [comment]
Which `predict.py` file? There is one in `scripts/pipeline` and also `scripts/reader`.

If you have run `download.sh`, `data/datasets/SQuAD-v1.1-dev.json` is an example JSON input to `scripts/reader/predict.py` and `data/datasets/SQuAD-v1.1-dev.txt` is an example input file to `scripts/pipeline/predict.py`.
