### ISSUE TITLE
how to use a text document as the knowledge base to perform Question answering on that document

### ISSUE THREAD

**Issue by monark12** [facebookresearch/DrQA#39]
I have a some pdf files of some reference books and I converted it to .txt format. It is a raw text data. I want to perform Question answering over these text documents. How will I do it? Please can anyone help me with this.

**Comment by hattek** [comment]
Kind of wondering this myself. How to turn this into a closed domain Q&A?

**Comment by ajfisch** [comment]
Please see the [README](https://github.com/facebookresearch/DrQA/blob/master/scripts/retriever/README.md) on the retriever to see how to build your own custom database + document retriever to feed to the document reader.

**Comment by hattek** [comment]
I was able to create a sqlite db earlier as a test, but after deleting the initial test db, I tried again a several hours later and got an UnicodeDecodeError: utf-8 codec can't decode byte 0xf9 in position 98: invalid start byte.

The text document has the same format as in the Readme: {"id": "doc1", "text": "text of doc1"}

Is there something I missed?

Full error message:

$ python build_db.py /home/HT/DrQA/data/test/ /home/HT/DrQA/data/test/test.db
10/02/2017 10:52:12 AM: [ Reading into database... ]
  0%|                                                     | 0/2 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/HT/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "build_db.py", line 72, in get_contents
    for line in f:
  File "/home/HT/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 98: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build_db.py", line 136, in <module>
    args.data_path, args.save_path, args.preprocess, args.num_workers
  File "build_db.py", line 109, in store_contents
    for pairs in tqdm(workers.imap_unordered(get_contents, files)):
  File "/home/HT/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:
  File "/home/HT/anaconda3/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 98: invalid start byte
