### ISSUE TITLE
Develop in windows

### ISSUE THREAD

**Issue by PrinceP** [facebookresearch/DrQA#4]
AttributeError: '_io.TextIOWrapper' object has no attribute 'split' in setup.py at `reqs.strip().split('\n')`

1. Changed 
`with open('README.md') as f:
    readme = f.read()`
with 
`readme = open('README.md', encoding="utf8")`

**Comment by ajfisch** [comment]
Hi @PrinceP!

Thank you for checking out the repo. Unfortunately DrQA does not support Windows. It was developed and tested for Linux/OSX (I don't use Windows and neither do my collaborators) -- that error is likely the first of many incompatibilities. I think we can setup a Docker image soon though.

I'll add a note about this to the README.
