### ISSUE TITLE
Cannot allocate memory when the pipeline is used

### ISSUE THREAD

**Issue by canguezelhan** [facebookresearch/DrQA#40]
Hello,

I am trying to use the pipeline with my own database, which contains 50 files. When I execute the script for the pipeline, it works fine. However, when I try to process a question, it crashes. 
   
    (py36) can@can-VirtualBox:~/DrQA$ python scripts/pipeline/interactive.py --reader-model data/reader/multitask.mdl --retriever-model data/manuals-tfidf-ngram\=2-hash\=16777216-tokenizer\=corenlp.npz --doc-db data/manuals.db --tokenizer corenlp
    09/25/2017 04:20:50 PM: [ Running on CPU only. ]
    09/25/2017 04:20:50 PM: [ Initializing pipeline... ]
    09/25/2017 04:20:50 PM: [ Initializing document ranker... ]
    09/25/2017 04:20:50 PM: [ Loading data/manuals-tfidf-ngram=2-hash=16777216-tokenizer=corenlp.npz ]
    09/25/2017 04:20:52 PM: [ Initializing document reader... ]
    09/25/2017 04:20:52 PM: [ Loading model data/reader/multitask.mdl ]
    09/25/2017 04:20:58 PM: [ Initializing tokenizers and document retrievers... ]

    Interactive DrQA  
    >> process(question, candidates=None, top_n=1, n_docs=5)
    >> usage()

    >>> process('Which one of the following would stop the machine if two plugs at the same time would enter into one of the channels located on the hopper drum?')
    09/25/2017 04:21:14 PM: [ Processing 1 queries... ]
    09/25/2017 04:21:14 PM: [ Retrieving top 5 docs... ]
    09/25/2017 04:21:31 PM: [ Reading 5 paragraphs... ]
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/home/can/anaconda3/envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/home/can/anaconda3/envs/py36/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
        pool._maintain_pool()
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
        self._repopulate_pool()
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
        w.start()
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 105, in start
        self._popen = self._Popen(self)
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
        return Popen(process_obj)
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
        self._launch(process_obj)
      File "/home/can/anaconda3/envs/py36/lib/python3.6/multiprocessing/popen_fork.py", line 67, in _launch
        self.pid = os.fork()
    OSError: [Errno 12] Cannot allocate memory

From other issues that are posted here, and from the error, I understand that the allocated memory is not enough. I am using an Ubuntu VirtualBox to run the script and the system has access to 4 GB RAM.

In one post, it is said that >20 GB RAM would be needed to use Wikipedia articles. Most of it is allocated to load the TF-IDF model, isn't it ? My TF-IDF model is 205 MB. Is it possible to estimate the memory usage of the Document Reader module ? 

Thank you.

**Comment by amudhangunasekaran** [comment]
@canguezelhan could you please be kind enough to give a detailed steps on how to create our own database? Lets say (for simplicity), I have one text file with some raw data. How can I convert it it to my own DB which I can feed to the pipeline?
The instructions in the drqa/scripts/retriever/README.MD starts with the assumption that the input file is already in the expected json format {"id":"title", "text":"value"}
How can I convert a raw data into this format and create a DB and then the tfidf format and feed it into the pipeline?

Could you please explain how you managed to do it?

Thanks!
~Amudhan

**Comment by ajfisch** [comment]
Hi @canguezelhan,

In addition to the tf-idf model the pipeline also loads tokenizers. The Stanford tokenizer is a bit more memory intensive. It might also cause over-commit of virtual memory.

Do you reproduce the error when using a different tokenizer (say spacy or regexp)? Is overcommit enabled?

**Comment by canguezelhan** [comment]
Hello @ajfisch,

Yes, I have the same error when I use spacy too.

Overcommit is also enabled (i.e., /proc/sys/vm/overcommit_memory is set to 0). I also tried the script with this flag set to 1, and in this case the process gets killed by the kernel.

**Comment by canguezelhan** [comment]
Hi @amudhangunasekaran,

I just followed the instructions in the retriever [README](scripts/retriever/README.md). As you said, in order to create a sqlite db, you need to provide a corpus of json files. Therefore, you need to create a json file for each text file you want to use in your db. Basically, given a text file filename.txt, create a new file filename.json and write {"id":"title", "text":"content of filename.txt"} to it. Then, just run the scripts as instructed:

    python build_db.py /data/json_files/ /data/database.db
 
Then,

    python build_tfidf.py /data/database.db /data/

I hope I could help. :)

**Comment by amudhangunasekaran** [comment]
@canguezelhan, Thanks a lot!! I was able to use a small set of data and create the DB and TF-IDF files and use it in the pipeline to get the answers! Really appreciate your help!

Best Regards,
Amudhan.

**Comment by canguezelhan** [comment]
Now I am using a server with 32GB RAM, and it is working.
