### ISSUE TITLE
Use of manual features in the model.py

### ISSUE THREAD

**Issue by rsanjaykamath** [facebookresearch/DrQA#41]
Hello,

Could you please highlight how you use the manual features which is extracted from build_feature_dict in utils.py, in the model.py

I could see its been passed as an argument for RnnDocReader, but couldn't figure how it is being used in the model or in the rnn_reader.

Thanks

**Comment by ajfisch** [comment]
They are appended to the document representation: see https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/rnn_reader.py#L117-L119.

See also section 3.2 of the referenced paper.
