### ISSUE TITLE
clear doubts

### ISSUE THREAD

**Issue by Nick7hill** [facebookresearch/DrQA#44]
hi, can anyone please tell me the difference between the reader sections in DrQA/drqa/reader and DrQA/scripts/reader. what exactly is going in these two sections and the aim for it?

**Comment by ajfisch** [comment]
The `DrQA/drqa` directory contains the source code for the `drqa` package. All of the model logic is here. The `DrQA/scripts` directory contains examples that use the package to do useful things with real things. Like train models. Build datasets. Make predictions.
