### ISSUE TITLE
Option to load multiple DrQA pipeline

### ISSUE THREAD

**Issue by raisudeen** [facebookresearch/DrQA#46]
Hi,
     First of all, Tons of thanks for this repo. I would like to load multiple DrQA Pipeline to serve specific users separately. i.e., there are so many individual group of documents. I should serve answers for specific people from specific group of documents. So, I planned to load multiple DrQA pipeline using web server. I chose Flask/Tornado web server to serve the DrQA results. But, due to multiple loading of DrQA, resources exceeds (each core allocated for each DrQA pipeline) and I couldn't load more DrQA pipeline.

    Is there any option to use DrQA with web server along with multi model loading?
-Raisudeen.

**Comment by ajfisch** [comment]
Not that we have implemented. While some care was given to make this implementation efficient, it is not really a production optimized repository.
