### ISSUE TITLE
answering from the given candidates

### ISSUE THREAD

**Issue by anand-ar** [facebookresearch/DrQA#47]
Suppose I want to give a passage and do not want to consider any other docs from wiki what is the use model

process(question, candidates) does not seem to look at candidates at all - still fetching it from wiki docs

Thanks

**Comment by ajfisch** [comment]
You want to just use the DocReader. Check out the readme here for some examples:
https://github.com/facebookresearch/DrQA/tree/master/scripts/reader#interactive

The candidates option will only filter valid spans from the given documents. If the candidate doesn't appear in the documents, it will not be chosen.

An example of using candidates with the interactive reader:

```
>>> process('Hi my name is Adam. Or is it Bob?', 'What is my name?', top_n=5)
+------+---------------------+------------+
| Rank |         Span        |   Score    |
+------+---------------------+------------+
|  1   |         Adam        |  0.88249   |
|  2   |        Adam.        | 0.0461305  |
|  3   |  Adam. Or is it Bob | 0.0295855  |
|  4   |  Hi my name is Adam | 0.00254033 |
|  5   | Adam. Or is it Bob? | 0.00112303 |
+------+---------------------+------------+
Time: 0.0941
>>> process('Hi my name is Adam. Or is it Bob?', 'What is my name?', candidates=['Adam', 'Bob'], top_n=5)
+------+------+------------------+
| Rank | Span |      Score       |
+------+------+------------------+
|  1   | Adam |  0.882489664641  |
|  2   | Bob  | 0.00100425823512 |
+------+------+------------------+
Time: 0.3132
```

**Comment by anand-ar** [comment]
Thanks

Another question:

how is --candidate-file used? does it need to be first used for prediction before using it in interactive session? is there a example usage? what exactly are candidates? are they passages/docs concatenated in one file?

Also, suppose I want the answer to be only from say 10 paragraphs what is the best option? - create a candidate file with those 10 paragraphs and then run prediction/interactive questioning?

**Comment by ajfisch** [comment]
A description of how `--candidates-file` is used is in the `--help` string: 

```
--candidate-file      List of candidates to restrict predictions to, one candidate per line.
```

This will be a global set of candidates, used for all questions. 

An example candidate file is `data/datasets/WikiMovies-entities.txt`. You can demonstrate its usage by running the eval on the WikiMovies dataset with this path set. 

Candidates are the set of valid possible answers, like multiple choice (with a lot of choices). If given, the system still doesn't leverage the list in any fancy way. But it can help if you have it.
