### ISSUE TITLE
CoreNLP tokenizer never quits

### ISSUE THREAD

**Issue by nlothian** [facebookresearch/DrQA#49]
When using DrQA as a library configured to use the CoreNLP tokenizer, each prediction made will start a new Java CoreNLP process. These processes never quit until the parent Python process quits.

https://github.com/facebookresearch/DrQA/pull/48 is a pull request to fix this.

**Comment by nlothian** [comment]
If someone is looking for something to do, I've found the CoreNLP HTTP server works quite well and avoids the heavy startup time for CoreNLP. It wouldn't be hard to write a new tokenizer using that interface. (I'm not a maintainer and have no association with the project other than a user though)

Docs: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

I may do that at some point, but this pull request fixes the immediate bug.

**Comment by ajfisch** [comment]
Commented on #48.
