### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by POMCP** [facebookresearch/DrQA#54]
While building the tfidf model i get the brokenpipe error after the batch 9 of 11.
Any ideas as to what could be going wrong?

System: MacBook Pro
macOS: Sierra/3.3GHz intel core i7/16G memory

**Comment by ajfisch** [comment]
Can you post the full script output?

**Comment by ajfisch** [comment]
Closing due to lack of response. Feel free to reopen if you still have the problem (and can give more context).

**Comment by H0key-22** [comment]
I have the same question!

**Comment by H0key-22** [comment]
> While building the tfidf model i get the brokenpipe error after the batch 9 of 11. Any ideas as to what could be going wrong?
> 
> System: MacBook Pro macOS: Sierra/3.3GHz intel core i7/16G memory

how do you fix it?
