### ISSUE TITLE
Doc Score

### ISSUE THREAD

**Issue by wendychin** [facebookresearch/DrQA#55]
trying to retrain the model using own dataset, would like to know the performance of the re-trained model by calculating the answer and doc score. Any formula that I can refer to? 

Btw, it's a robust system, thanks for the share!

**Comment by ajfisch** [comment]
Hi @wendychin,

Could you explain more what you would like to do? For our evaluation, we reported accuracies in terms of exact match for answers for the DocReader and recall in the top K documents for the DocRetriever.

Examples of these evaluations can be found in `scripts/retriever/eval.py`, `scripts/pipeline/eval.py`, and the official SQuAD eval from stanford-qa.com.

**Comment by zgp1990** [comment]
hello, @ajfisch  . I also have a question about doc score.
i am an engineer in CHINA . I download your python program and train my own  model.
But my dataset language is Chinese and recall in the top K documents is bad.
Even the score is a same value：90.545

( I change ner language to chinese)

**Comment by ajfisch** [comment]
@zgp1990, I'm sorry I don't have enough context to debug Chinese. My advice would be to debug the TF-IDF building steps for your model and tokenizer.

**Comment by zgp1990** [comment]
@ajfisch  thx~
i have solved this problem. CoreNlp tokenizer has Strict checks , this string can't be null
