### ISSUE TITLE
retrieval accuracy on CuratedTrec dataset is only 31.27%

### ISSUE THREAD

**Issue by csarron** [facebookresearch/DrQA#56]
Hi there, I followed the instructions in the readme, but for trec dataset, I could only get 31.27% retrieval accuracy instead of 87.6% as you claimed.

here is what I ran:
`python scripts/retriever/eval.py data/datasets/CuratedTrec-test.txt`
below is the output:
```
CuratedTrec-test.txt
Examples:                       694
Matches in top 5:               217
Match % in top 5:               31.27
Total time:                     121.3428 (s)
```

**Comment by ajfisch** [comment]
The TREC dataset answers are in the form of regular expressions, not strings. You need to use the `--match regex` option.
```
python scripts/retriever/eval.py data/datasets/CuratedTrec-test.txt --match regex

CuratedTrec-test.txt
Examples:			694
Matches in top 5:		608
Match % in top 5:		87.61
Total time:			55.7219 (s)
```

**Comment by csarron** [comment]
Got it, thanks for the quick reply
