### ISSUE TITLE
Error with CoreNLPTokenizer

### ISSUE THREAD

**Issue by hongweizeng** [facebookresearch/DrQA#61]
I just want to verify the CoreNLPTokenizer works, then met the TIMEOUT error
![image](https://user-images.githubusercontent.com/15373554/32855436-94c861e8-ca7c-11e7-80e2-94ea4acb8f30.png)

**Comment by ajfisch** [comment]
Does the CoreNLP java installation work from the command line directly?

**Comment by xjtu-zeng** [comment]
The same error appeared.
![image](https://user-images.githubusercontent.com/15373554/32879337-92aabb8c-cae4-11e7-8c50-af2a285483c4.png)

**Comment by ajfisch** [comment]
That is not what I meant by running the java jars from the command line directly: 

```
java edu.stanford.nlp.pipeline.StanfordCoreNLP`
```

**Comment by ajfisch** [comment]
Closing due to being quiet for some time. Feel free to reopen if your issue persists!

**Comment by Miopas** [comment]
I met the same problem and solved it currently.

In my situation, it's just because I forgot to run `source ~/.bashrc` after running `./install_corenlp.sh`。

**Comment by Arjunsankarlal** [comment]
I did installed CoreNLP, exported the path, ran source ~/.bashrc but still I am getting the timeout issue

> pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10369a6d8>
command: /bin/bash
args: ['/bin/bash']
buffer (last 100 chars): b' Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP\r\n(ZiaBiMPMvenv) '
before (last 100 chars): b' Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP\r\n(ZiaBiMPMvenv) '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 64557
child_fd: 8
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 100000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'NLP>'"

**Comment by aforever** [comment]
> I met the same problem and solved it currently.
> 
> In my situation, it's just because I forgot to run `source ~/.bashrc` after running `./install_corenlp.sh`.



> I did installed CoreNLP, exported the path, ran source ~/.bashrc but still I am getting the timeout issue
> 
> > pexpect.exceptions.TIMEOUT: Timeout exceeded.
> > <pexpect.pty_spawn.spawn object at 0x10369a6d8>
> > command: /bin/bash
> > args: ['/bin/bash']
> > buffer (last 100 chars): b' Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP\r\n(ZiaBiMPMvenv) '
> > before (last 100 chars): b' Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP\r\n(ZiaBiMPMvenv) '
> > after: <class 'pexpect.exceptions.TIMEOUT'>
> > match: None
> > match_index: None
> > exitstatus: None
> > flag_eof: False
> > pid: 64557
> > child_fd: 8
> > closed: False
> > timeout: 60
> > delimiter: <class 'pexpect.exceptions.EOF'>
> > logfile: None
> > logfile_read: None
> > logfile_send: None
> > maxread: 100000
> > ignorecase: False
> > searchwindowsize: None
> > delaybeforesend: 0
> > delayafterclose: 0.1
> > delayafterterminate: 0.1
> > searcher: searcher_string:
> > 0: "b'NLP>'"
> 
> I am running the same code from pyCharm

In your shell environment, you should run source ~/.bashrc, and then in the same shell run python scripts/pipeline/interactive.py

**Comment by cs145442** [comment]
I had the exact same issue but was saved by your comment. (My ubuntu wasn't preloaded with deafult-jre, which I did install and things were butter smooth.) Thanks.

> That is not what I meant by running the java jars from the command line directly:
> 
> ```
> java edu.stanford.nlp.pipeline.StanfordCoreNLP
> ```
> 
> If you have added this to your CLASSPATH properly this should output something like:
> 
> ```
> [afisch/~/github/DrQA: (master)]$ java edu.stanford.nlp.pipeline.StanfordCoreNLP
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... not found.
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: edu/stanford/nlp/pipeline/StanfordCoreNLP.properties ... found.
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
> [main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.3 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
> [main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [2.0 sec].
> [main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.9 sec].
> [main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [1.0 sec].
> [main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
> [main] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
> [main] INFO edu.stanford.nlp.parser.nndep.Classifier - PreComputed 99996, Elapsed Time: 19.652 (s)
> [main] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Initializing dependency parser ... done [22.9 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
> [main] INFO edu.stanford.nlp.pipeline.MentionAnnotator - Using mention detector type: dependency
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
> ```
