### ISSUE TITLE
Document Reader Preprocessing.

### ISSUE THREAD

**Issue by samdash** [facebookresearch/DrQA#62]
I need help, what is the format that is required to preprocess my data using preprocess.py? 
is below format required? 
```
'{"question": "q1", "answer": ["a11", ..., "a1i"]}'
'{"question": "qN", "answer": ["aN1", ..., "aNi"]}'
```

Or SQuAD format as shown below? if so how do i generate below format?

```
file.json
├── "data"
│   └── [i]
│       ├── "paragraphs"
│       │   └── [j]
│       │       ├── "context": "paragraph text"
│       │       └── "qas"
│       │           └── [k]
│       │               ├── "answers"
│       │               │   └── [l]
│       │               │       ├── "answer_start": N
│       │               │       └── "text": "answer"
│       │               ├── "id": "<uuid>"
│       │               └── "question": "paragraph question?"
│       └── "title": "document id"
└── "version": 1.1

```

as mentioned here : https://github.com/facebookresearch/DrQA/blob/master/scripts/reader/README.md

**Comment by ajfisch** [comment]
Yes, as it says in the README, you need SQuAD formatted data. If it is your own data, you need to format it yourself.

**Comment by samdash** [comment]
what is the purpose of this format? And how it can be used ?

```
'{"question": "q1", "answer": ["a11", ..., "a1i"]}'
'{"question": "qN", "answer": ["aN1", ..., "aNi"]}'
```

**Comment by ajfisch** [comment]
This is all described in the [data](https://github.com/facebookresearch/DrQA#qa-datasets) section in the README. Formats A and B.
