### ISSUE TITLE
How to increase length of the span?

### ISSUE THREAD

**Issue by samdash** [facebookresearch/DrQA#63]
Hi Adam,

while executing  below statement, i see the span only have few words, how to increase the length of th e span to get better meaning

`python scripts/pipeline/predict.py /path/to/format/A/dataset.txt
`

below is the sample i get when executing the predict.py, is there any fine tuning the span attribute to increase the length? 

```
 "span": "a recommended update", "doc_score": 91.32551502098157, "span_score": 45858.703125}]
 "span": "included.Aperture 3", "doc_score": 195.0124505464773, "span_score": 7517108.0}]
 "span": "2nd generation", "doc_score": 51.732084228252496, "span_score": 1008.5970458984375}]
 "span": "2 Help", "doc_score": 64.38085395815739, "span_score": 142660.265625}]
 "span": "youre", "doc_score": 87.41417707786954, "span_score": 2699.703125}]
```

**Comment by ajfisch** [comment]
You can look at the context by specifying `return_context=True` in the `DrQA.process` function. See https://github.com/facebookresearch/DrQA/blob/master/scripts/pipeline/interactive.py#L80-L82 for an example.

**Comment by samdash** [comment]
Thanks Adam, I see that when i do `return_context =True` it also returns the context , however i was asking if it is possible to expand the Span attribute length  to see more meaningful data as apposed to single word ?

**Comment by ajfisch** [comment]
You can do it manually. The context is returned with the span offsets which you can increase. Otherwise, train it with longer spans.

**Comment by samdash** [comment]
Can you let me know how can i do it manually to increase the span offsets?

**Comment by ajfisch** [comment]
https://github.com/facebookresearch/DrQA/blob/master/scripts/pipeline/interactive.py#L80-L82

Add +- some offset to `start` and `end`

**Comment by samdash** [comment]
Thanks Adam, will do that and see.

**Comment by ajfisch** [comment]
Add some +/- offset to `s` and `e` here https://github.com/facebookresearch/DrQA/blob/master/drqa/pipeline/drqa.py#L290
