### ISSUE TITLE
Error while training with fastText embeddings

### ISSUE THREAD

**Issue by kickbox** [facebookresearch/DrQA#66]
I get an assertion error at  `assert(len(parsed) == embedding.size(1) + 1)`. Is this because I am using fastText instead of Glove embeddings? How can I resolve this...

```
12/01/2017 10:40:19 AM: [ Loading pre-trained embeddings for 78920 words from /home/user/data/embeddings/wiki.en.vec ]
Traceback (most recent call last):
  File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 402, in main
    model = init_from_scratch(args, train_exs, dev_exs)
  File "scripts/reader/train.py", line 197, in init_from_scratch
    model.load_embeddings(word_dict.tokens(), args.embedding_file)
  File "/home/user/DrQA/drqa/reader/model.py", line 109, in load_embeddings
    assert(len(parsed) == embedding.size(1) + 1)
AssertionError
```
Update: I can confirm that this error disappeared after using glove. I am interested in using fastText as I want uncassed embeddings...

**Comment by ajfisch** [comment]
You’ll need to remove the first line of the fasttext file — unlike glove it starts with a mind stating the vocab size

**Comment by kickbox** [comment]
Thank you @ajfisch. I was able to remove the first line with this command `tail -n +2 "fastText" > "file2"`
