### ISSUE TITLE
docs.db -> database is locked error

### ISSUE THREAD

**Issue by aagohary** [facebookresearch/DrQA#69]
Hi,
I am trying to run the distant supervision script, but I keep getting the error  "database is locked"
in the fetch_text phase. I redownloaded a clean copy of docs.db and tried to query is with sqlit3 outside of the python script, and I still keep getting the same error.

**Comment by ajfisch** [comment]
Is your db on a NFS volume or on local disk? I've seen this error with sqlite and NFS before.

**Comment by aagohary** [comment]
yes on an NSF volume.

**Comment by ajfisch** [comment]
If I recall, I was not able to make it work on NFS. Something to do with NFS and sqlite file lock interaction.

The internet suggests doing a dummy copy of the db to release the stale NFS lock. But it might just lock again.

**Comment by aagohary** [comment]
Thanks. copying the db to a local storage solved the problem.
