### ISSUE TITLE
prediction.json

### ISSUE THREAD

**Issue by waheedabro** [facebookresearch/DrQA#70]
Hello, I'm new to machine reading i read your paper and tons of thanks for this repo. 

I have run model predictions on a dataset using below its working fine:
python scripts/reader/predict.py data/datasets/SQuAD-v1.1-dev.json --model data/reader/single.mdl

Now i want to evaluate reader performance using below command 

python scripts/reader/official_eval.py data/datasets/SQuAD-v1.1-dev.json /path/to/predictions/with/--official/flag/set.json

 But i don't understand "/path/to/predictions/with/--official/flag/set.json" from where i can get this file.

Thanks for your time.

**Comment by ajfisch** [comment]
Those files don't preexist -- they're placeholders for the files that you create by running the first script.

So `/path/to/predictions/with/--official/flag/set.json` means "the path the file `predict.py` outputted when you ran it with the `--official` command line flag set. This file is a `.json` file."
