### ISSUE TITLE
[Question] Comparison - your Document Retriever vs Elasticsearch based Wikipedia Search

### ISSUE THREAD

**Issue by srotemal** [facebookresearch/DrQA#74]
Hi,
Thanks for the excellent system!
I have read the article and they have wrote:
"A simple inverted index lookup followed by term vector model scoring performs quite well on this task for many question types, compared to the built-in ElasticSearch based Wikipedia Search API (Gormley and Tong, 2015). "

Have you made aby numerical comparison of the final system to ElasticSearch based Wikipedia Search API?

Thanks!

**Comment by ajfisch** [comment]
Yes, these results are in Table 3 of the paper.

**Comment by srotemal** [comment]
Thanks Adam!
