### ISSUE TITLE
setting the default language for CoreNLP

### ISSUE THREAD

**Issue by MacXing** [facebookresearch/DrQA#84]
Hi Adam,
Thank you
I know where DrQA is setting the default language for CoreNLP, where is the file linking corenlp?

**Comment by ajfisch** [comment]
I'm not sure I understand your question? CoreNLP is accessed using the Java CLASSPATH environment variable. The wrapper for CoreNLP is in `drqa/tokenizers/corenlp_tokenizer.py`.

**Comment by MacXing** [comment]
Hi Adam,
Thank you repty,

328/5000
Wǒ de shùjù jí shì formatA, wǒ xiǎng xùnliàn zìjǐ de móxíng, dànshì méiyǒu xiàng Squad yīyàng de shùjù, suǒyǐ zhǐ néng yòng DS, dànshì zài xùnliàn de shíhòu, yīzhí méiyǒu jiéshù, yě méiyǒu jiéguǒ, wǒ tiáoshì shì tíng zàile:
With ThreadPool(num_workers) as threads:
Closest_docs = partial(self.Closest_docs, k=k)
#print(closest_docs)
results = threads.Map(closest_docs, queries)
wǒ yòngle map_async chūxiàn de jiéguǒ wèi None, shì bùshì shùjù yǒu wèntí, suǒyǐ shì bùshì corenlp chūxiànle fēncí wèntí
My dataset is formatA. I want to train my model, but I do not have the same data as Squad, so I can only use DS. But when I was training, I did not finish it. There was no result. My debugging was stopped:
         with ThreadPool (num_workers) as threads:
             closest_docs = partial (self.closest_docs, k = k)
             #print (closest_docs)
             results = threads.map (closest_docs, queries)
I used map_async the result is None, the data is not a problem, so is there corenlp segmentation problem
thank you

**Comment by MacXing** [comment]
My dataset is formatA. I want to train my model, but I do not have the same data as Squad, so I can only use DS. But when I was training, I did not finish it. There was no result. My debugging was stopped:
         with ThreadPool (num_workers) as threads:
             closest_docs = partial (self.closest_docs, k = k)
             #print (closest_docs)
             results = threads.map (closest_docs, queries)
I used map_async the result is None, the data is not a problem, so is there corenlp segmentation problem

**Comment by ily666666** [comment]
hello,MacXing how to set other language?Thank you

**Comment by ily666666** [comment]
can you help me

**Comment by ajfisch** [comment]
Chinese or other languages aren't supported here for DrQA, to figure out about the CoreNLP parser you can check out https://stanfordnlp.github.io/CoreNLP/ and https://github.com/stanfordnlp/CoreNLP.

**Comment by MacXing** [comment]
下载其他语言的jar包，加入stanfordnlp core里，配置好stanford nlp 然后里面有一个.py文件 我忘了  里面
java -c ....因为这个corenlp是java写得，python调它需要通过其他方式，你找到那个地方就可以修改了，具体修改看stanford corenlp官网

**Comment by ily666666** [comment]
大佬，你有修改好的文件么，我改了但是没用啊

**Comment by MacXing** [comment]
我好久以前的了，改不难，改corenlp_tokenzier     annotators = ['tokenize', 'ssplit']
        if 'ner' in self.annotators:
            annotators.extend(['pos', 'lemma', 'ner'])
        elif 'lemma' in self.annotators:
            annotators.extend(['pos', 'lemma'])
        elif 'pos' in self.annotators:
            annotators.extend(['pos'])
        annotators = ','.join(annotators)
        options = ','.join(['untokenizable=noneDelete',
                            'invertible=true'])

        cmd = ['java -mx5g -cp "/home/innovate/zhouxing/stanford-corenlp-full/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties',' -annotators ',annotators,
               ' -outputFormat', 'json', ' -prettyPrint', 'false','-tokenize.options', options,
               ]

**Comment by ily666666** [comment]
那您的意思是改完之后
from drqa.tokenizers import CoreNLPTokenizer
tok = CoreNLPTokenizer()
tok.tokenize('hello world').words() 
比如，这些个语句就可以处理中文了是吗

**Comment by MacXing** [comment]
那个文件修改是指运行DrQA的时候处理中文，如何你只是用上面的语句处理中文，需要另外改，你可以看看stanford CoreNLP官网，有介绍的

**Comment by ily666666** [comment]
我以为这些个语句就是drqa中的封装语句
你看他from drqa.tokenizers import CoreNLPPTkoenizer

**Comment by MacXing** [comment]
你仔细看看官网，里面有介绍怎么使用其他语言的

**Comment by ily666666** [comment]
好的，谢谢你，请问你当初成功处理了中文QA问题了吗，最后结果怎么样啊

**Comment by MacXing** [comment]
最终完成了，就是没有好的数据集，不是很准

**Comment by ily666666** [comment]
嗯，您介意我测试一下吗###  逃:)，
