### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by exelents** [facebookresearch/DrQA#86]
Hello.
How much memory do I need to run your QA system? Is all 25 GB of untarred data uploaded to memory?
When I tried to launch interactive mode i got an error:

> [exelents@archlinux DrQA]$ python3 scripts/pipeline/interactive.py
> 01/20/2018 05:25:35 PM: [ Running on CPU only. ]
> 01/20/2018 05:25:35 PM: [ Initializing pipeline... ]
> 01/20/2018 05:25:35 PM: [ Initializing document ranker... ]
> 01/20/2018 05:25:35 PM: [ Loading /mnt/d/DrQA/data/wikipedia/docs-tfidf-ngram=2-hash=16777216-tokenizer=simple.npz ]
> Traceback (most recent call last):
>   File "scripts/pipeline/interactive.py", line 70, in <module>
>     tokenizer=args.tokenizer
>   File "/mnt/d/DrQA/drqa/pipeline/drqa.py", line 109, in __init__
>     self.ranker = ranker_class(**ranker_opts)
>   File "/mnt/d/DrQA/drqa/retriever/tfidf_doc_ranker.py", line 37, in __init__
>     matrix, metadata = utils.load_sparse_csr(tfidf_path)
>   File "/mnt/d/DrQA/drqa/retriever/utils.py", line 34, in load_sparse_csr
>     matrix = sp.csr_matrix((loader['data'], loader['indices'],
>   File "/usr/lib/python3.6/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
>     pickle_kwargs=self.pickle_kwargs)
>   File "/usr/lib/python3.6/site-packages/numpy/lib/format.py", line 671, in read_array
>     array = numpy.ndarray(count, dtype=dtype)
> MemoryError

**Comment by ajfisch** [comment]
Around 15 GB of RAM should be sufficient to run the full system. Less for just the Document Reader. (Loading the tfidf Document Retriever for Wikipedia is costly).

**Comment by exelents** [comment]
Thank you.
