### ISSUE TITLE
hosting DrQA

### ISSUE THREAD

**Issue by piyank22** [facebookresearch/DrQA#87]
Hi Adam,
I was trying to host DrQA on AWS Beanstalk, and despite trying everything i am not able to run the DrQA.process function smoothly in it.
the code works perfectly fine on my localhost , something which takes 9 sec on my pc is getting stuck and cant seem to evaluate any further requests once its stuck.
I know this is NOT a ISSUE , but i need some help around this problem.
thanks 
if you know something which is very obvious i have not thought of please point it out, else i ll post all the details.

**Comment by ajfisch** [comment]
I’m not familiar with the AWS environment you’re using, but happy to try to help. Go ahead and post all the details, it will probably only help.

**Comment by piyank22** [comment]
I was able to solve it by changing all the async process to sync process.

**Comment by shubhank008** [comment]
@piyank22 @ajfisch Facing this same problem where on exact same environments and setups, it works on my local PC/machine with Nvidia 1070 but it gets stuck at reading paragraphs (pipeline/interactive) and never proceeds further even after 30 mins when using AWS EC2 instance (which has a K80 GPU).  

Tried both CoreNLP and Spacy tokenizers.

@piyank22 can you please provide the exact edits you made to change the async to sync for it to work ?
