### ISSUE TITLE
Add training question to Existing Multitask trained model 

### ISSUE THREAD

**Issue by shivamani-ans** [facebookresearch/DrQA#89]
What are minimum no of questions required to train existing model on specific domain and how to check whether trained model is working in retrieving results.

Can i get explanation on training model with questions ?

**Comment by ajfisch** [comment]
I don't know if I can quantify a minimum number of questions. It depends on the quality of the questions and how different the domain is from what the current models are trained on, i.e. if you can do just some fine-tuning. From scratch, you need 10s of thousands (SQuAD is 100k). For fine-tuning, perhaps just 100's or 1000's (CuratedTREC is only a couple hundred questions).

To check retrieved results you can use the interactive script in `scripts/retriever/interactive.py`.

**Comment by ajfisch** [comment]
Closing. If you continue to have questions, feel free to reopen.
