### ISSUE TITLE
ImportError: No module named 'pexpect'

### ISSUE THREAD

**Issue by loveJasmine** [facebookresearch/DrQA#9]
(VENVpytorch3) mldl@mldlUB1604:~/ub16_prj/DrQA$ sudo -H pip3 install pexpect 
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages
(VENVpytorch3) mldl@mldlUB1604:~/ub16_prj/DrQA$ 
(VENVpytorch3) mldl@mldlUB1604:~/ub16_prj/DrQA$ 
(VENVpytorch3) mldl@mldlUB1604:~/ub16_prj/DrQA$ 
(VENVpytorch3) mldl@mldlUB1604:~/ub16_prj/DrQA$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import drqa.reader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mldl/ub16_prj/DrQA/drqa/__init__.py", line 20, in <module>
    from . import tokenizers
  File "/home/mldl/ub16_prj/DrQA/drqa/tokenizers/__init__.py", line 20, in <module>
    from .corenlp_tokenizer import CoreNLPTokenizer
  File "/home/mldl/ub16_prj/DrQA/drqa/tokenizers/corenlp_tokenizer.py", line 14, in <module>
    import pexpect
ImportError: No module named 'pexpect'
>>>

**Comment by ajfisch** [comment]
It seems like you had a problem installing `pexpect`, or your `PYTHONPATH` is such that it can't find it.

Perhaps you could try:

`pip install -I pexpect`

`python -c 'import pexpect'`

Verify that whatever location pexpect was downloaded to in in your sys.path?

**Comment by loveJasmine** [comment]
fixed bu upgrade to pexpect-4.2.1
