### ISSUE TITLE
Do new QA datasets need additional training?

### ISSUE THREAD

**Issue by Depro20** [facebookresearch/DrQA#95]
Hi Adam, 
               Your repo has been super helpful. 
                I am using a Format A dataset of Q-A pairs. I have 2 questions:
1. Do I need to create a new Db with contextual documents to run the generate.py module under distant supervision, to be able to build dstrain and dsdev files?
2. Once the files above are generated, do I use the existing SQuAD models or do I need to rebuild a trained model from the new dataset?

Thanks

**Comment by ajfisch** [comment]
1. Yes, unless you plan to use Wikipedia.
2. I'd recommend using a pre-trained SQuAD model as an initialization, and then fine tuning on the distantly supervised data.

**Comment by Depro20** [comment]
Thanks Adam, 2 follow up queries on the second part:
1. You mention in the Distant Supervision Readme that it generates dstrain and dsdev that are preprocessed (hence don't need to go through the preprocessor step as in case of Format B), for document reader training. My question is, in what cases should we train using a particular dataset as opposed to using the pretrained SQuAD. 

2. Also, I tried running training on the outputted DStrain and DSdev files and it throws this error: 
`File "scripts/reader/train.py", line 542, in <module>
    main(args)
  File "scripts/reader/train.py", line 402, in main
    model = init_from_scratch(args, train_exs, dev_exs)
  File "scripts/reader/train.py", line 182, in init_from_scratch
    feature_dict = utils.build_feature_dict(args, train_exs)
  File "/Users/apple/Desktop/py/DrQA/old_dr/drqa/reader/utils.py", line 154, in build_feature_dict
    for w in ex['pos']:
TypeError: 'NoneType' object is not iterable`

Command run was this:                                                                   scripts/reader/train.py --embedding-file /Users/apple/Desktop/py/DrQA/old_dr/data/embeddings/glove.840B.300d.txt --tune-partial 1000 --train-file /Users/apple/Desktop/py/DrQA/old_dr/data/datasets/ds/QApandas.dstrain --dev-file /Users/apple/Desktop/py/DrQA/old_dr/data/datasets/ds/QApandas.dsdev 

What seems to be the problem here? Is it normal to have "pos" and "lemma" as null in the dstrain and dsdev files?

**Comment by ajfisch** [comment]
1. If the use case you're interested in testing on has a different distribution of questions from SQuAD (which it probably does) then it's a good idea to try to do some fine tuning of a pre-trained SQuAD model with some distantly supervised data. Using the original SQuAD model at least as a starting point for training is usually helpful.
2. The default in distance supervision is not to tag the more expensive POS/NER/LEMMA tags. So you'll need to turn those flags off (`--use-pos f`, `--use-ner f`, `--use-lemma` f).

**Comment by Depro20** [comment]
Thanks Adam. Will try these out.
