### ISSUE TITLE
Understanding doc score and span score

### ISSUE THREAD

**Issue by icegeek22** [facebookresearch/DrQA#96]
Can you please tell the significance of doc score and span score?
As I understand, the greater the scores, the more is the confidence in the answer. 
What I want to know is a minimum threshold value for these scores such that any docs having score less than the threshold can be immediately rejected, when the top 5 documents are retrieved?

**Comment by ajfisch** [comment]
Higher scores do mean higher confidence. The scores, however, aren't well calibrated and have large variance (a known flaw in the model), so defining fixed thresholds is hard. You can try to find some thresholds that work well for you empirically.
