### ISSUE TITLE
Bug in preprocess.py

### ISSUE THREAD

**Issue by divyansha** [facebookresearch/DrQA#97]
For some of the answers, in the file resulting from preprocess.py, the answer is an empty list, instead of actually containing values.

The very first example is the 5th answer in the file, where the answer in the processed file is [], although in the unprocessed dev file, the answer is ['gold', 'gold', 'gold'].

FYI, I used CoreNLP for the preprocessing

Please confirm whether this is actually a bug, or if I am missing something (eg: Are those questions to be ignored, and if so, why?)

**Comment by ajfisch** [comment]
This is not a bug. `preprocess.py` attempt to convert the (string, character offset) answers given in SQuAD to token offsets, as parsed by CoreNLP. Sometimes the SQuAD spans don't line up with CoreNLP tokens. (For that specific example, I believe it is splitting the `gold` from `gold-themed` which is parsed as a single token).

For training, we [ignore](https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/utils.py#L43)  examples that don't have answers. For official evaluation it doesn't matter, as we use the predicted strings directly.
