### ISSUE TITLE
bug in scripts/predict.py

### ISSUE THREAD

**Issue by shixing** [facebookresearch/DrQA#98]
line number 60:
predictor = Predictor(
    args.model,
    args.tokenizer,
    args.embedding_file,
    args.num_workers,
)

which should be : 

predictor = Predictor(
    model = args.model,
    tokenizer = args.tokenizer,
    embedding_file = args.embedding_file,
    num_workers = args.num_workers,
)

**Comment by ajfisch** [comment]
Good catch! Will fix.
